export const JOURNEYS = [
  {
    id: 'core', icon: '🏁', color: '#4A90E2',
    en: 'Core English', pt: 'Inglês Essencial',
    desc: { en: 'Build the foundation for everyday English', pt: 'Construa a base para o inglês cotidiano' },
    weeks: [
  { week:1, theme:{en:'Hello, English! — The Basics',pt:'Olá, Inglês! — O Básico'}, tasks:[
    {id:'ge1',en:'Watch: Present Simple explained simply (BBC Learning English)',pt:'Assista: Presente simples explicado de forma simples',cat:'grammar',link:'https://www.youtube.com/watch?v=oRMF5q6NFLI'},
    {id:'ge2',en:'Exercise: Practice the Present Simple — British Council',pt:'Exercício: Pratique o Presente Simples',cat:'grammar',link:'https://learnenglish.britishcouncil.org/grammar/a1-a2/present-simple'},
    {id:'ge3',en:'Watch: Articles — a, an, the — when to use each',pt:'Artigos: a, an, the — quando usar cada um',cat:'grammar',link:'https://www.youtube.com/watch?v=vSwMhWFJoY0'},
    {id:'ge4',en:'Exercise: Prepositions in, on, at — British Council',pt:'Exercício: preposições in, on, at',cat:'grammar',link:'https://learnenglish.britishcouncil.org/grammar/a1-a2/prepositions-place'},
    {id:'ge5',en:'Write 5 true sentences about yourself using present simple',pt:'Escreva 5 frases verdadeiras sobre você no presente simples',cat:'writing',
      variations:{
        beginner:{pt:'Escreva 5 frases simples sobre você no presente simples usando palavras que já conhece',en:'Write 5 simple sentences about yourself in the present simple using words you already know'},
        advanced:{pt:'Escreva 10 frases variadas sobre sua rotina e personalidade usando afirmativas, negativas e interrogativas no presente simples',en:'Write 10 varied sentences about your routine and personality using affirmative, negative and question forms in the present simple'},
      }},
  ]},
  { week:2, theme:{en:'Your First 100 Words',pt:'Suas Primeiras 100 Palavras'}, tasks:[
    {id:'ge6',en:'Study: 100 most common English words (Oxford list)',pt:'Estude: as 100 palavras mais comuns em inglês',cat:'vocab',link:'https://www.oxfordlearnersdictionaries.com/topic/'},
    {id:'ge7',en:'Watch: False friends — words that trick Brazilians (YouTube)',pt:'Falsos cognatos que enganam brasileiros',cat:'vocab',link:'https://www.youtube.com/results?search_query=false+friends+english+portuguese'},
    {id:'ge8',en:'Exercise: Everyday vocabulary — British Council A1',pt:'Exercício: vocabulário do dia a dia',cat:'vocab',link:'https://learnenglish.britishcouncil.org/vocabulary/a1-vocabulary'},
    {id:'ge9',en:'Listen: 6 Minute English — The value of the internet (BBC)',pt:'Ouça: 6 Minute English — episódio para iniciantes',cat:'listening',link:'https://www.bbc.co.uk/learningenglish/english/features/6-minute-english'},
    {id:'ge10',en:'Write 10 sentences using words you learned this week',pt:'Escreva 10 frases com palavras que aprendeu esta semana',cat:'writing',
      variations:{
        beginner:{pt:'Escreva 5 frases usando palavras novas desta semana — use um dicionário se precisar',en:'Write 5 sentences using new words from this week — use a dictionary if needed'},
        advanced:{pt:'Escreva 10 frases criativas conectando as palavras novas em um pequeno parágrafo com sentido',en:'Write 10 creative sentences connecting the new words into a small coherent paragraph'},
      }},
  ]},
  { week:3, theme:{en:'Understanding Spoken English',pt:'Entendendo o Inglês Falado'}, tasks:[
    {id:'ge11',en:'Listen: A1 Listening practice — British Council',pt:'Pratique a escuta no nível A1',cat:'listening',link:'https://learnenglish.britishcouncil.org/skills/listening/a1-listening'},
    {id:'ge12',en:'Watch: English with subtitles — BBC Learning English YouTube',pt:'Assista: inglês com legendas — BBC Learning English',cat:'listening',link:'https://www.youtube.com/@bbclearningenglish'},
    {id:'ge13',en:'Exercise: Listening for gist — what is the main idea?',pt:'Exercício: ouvir para entender a ideia geral',cat:'listening',link:'https://www.elllo.org/english/levels/index.htm'},
    {id:'ge14',en:'Listen to a song you like and try to write the chorus',pt:'Ouça uma música que você gosta e tente escrever o refrão',cat:'listening',
      variations:{
        beginner:{pt:'Ouça a música 3 vezes e tente escrever pelo menos 3 palavras do refrão que você reconhecer',en:'Listen to the song 3 times and try to write at least 3 words from the chorus that you recognize'},
        advanced:{pt:'Escreva o refrão inteiro de memória após ouvir, depois verifique a letra e corrija os erros',en:'Write the full chorus from memory after listening, then check the lyrics and correct your mistakes'},
      }},
    {id:'ge15',en:'Watch a 3-min video and write 3 things you understood',pt:'Assista um vídeo de 3 min e escreva 3 coisas que entendeu',cat:'listening',link:'https://www.bbc.co.uk/learningenglish/english/features/6-minute-english',
      variations:{
        beginner:{pt:'Assista com legendas em inglês e escreva 3 palavras novas que você viu',en:'Watch with English subtitles and write 3 new words you noticed'},
        advanced:{pt:'Assista sem legendas e escreva um resumo de 5 frases sobre o que entendeu',en:'Watch without subtitles and write a 5-sentence summary of what you understood'},
      }},
  ]},
  { week:4, theme:{en:'Say It Out Loud',pt:'Fale em Voz Alta'}, tasks:[
    {id:'ge16',en:'Watch: How to introduce yourself in English (step by step)',pt:'Como se apresentar em inglês passo a passo',cat:'speaking',link:'https://www.youtube.com/results?search_query=how+to+introduce+yourself+in+english+beginners'},
    {id:'ge17',en:'Practice: Small talk phrases — weather, weekends, hobbies',pt:'Frases de conversa casual: clima, fds, hobbies',cat:'speaking',link:'https://learnenglish.britishcouncil.org/skills/speaking/a2-speaking/making-conversation'},
    {id:'ge18',en:'Watch: How to ask questions in English — BBC',pt:'Como fazer perguntas em inglês',cat:'speaking',link:'https://www.youtube.com/watch?v=Sj_6JjJPBtQ'},
    {id:'ge19',en:'Record yourself: introduce yourself in 60 seconds (use Vocaroo)',pt:'Grave-se: apresente-se em 60 segundos',cat:'speaking',link:'https://vocaroo.com',
      variations:{
        beginner:{pt:'Grave-se dizendo seu nome, onde mora e uma coisa que você gosta — use um roteiro escrito se precisar',en:'Record yourself saying your name, where you live and one thing you like — use a written script if you need to'},
        advanced:{pt:'Grave-se se apresentando por 60–90 segundos sem roteiro: nome, profissão, hobbies, e por que está aprendendo inglês',en:'Record yourself presenting for 60–90 seconds without a script: name, job, hobbies and why you are learning English'},
      }},
    {id:'ge20',en:'Send your recording to Teacher Renata for feedback',pt:'Envie sua gravação para Teacher Renata',cat:'speaking'},
  ]},
  { week:5, theme:{en:'Reading Without Fear',pt:'Leitura Sem Medo'}, tasks:[
    {id:'ge21',en:'Read: A1 level story — British Council (with exercises)',pt:'Leia: história nível A1 com exercícios',cat:'reading',link:'https://learnenglish.britishcouncil.org/skills/reading/a1-reading'},
    {id:'ge22',en:'Strategy: Skim the text — find the main idea in 2 minutes',pt:'Estratégia: varredura — encontre a ideia principal em 2 min',cat:'reading',link:'https://learnenglish.britishcouncil.org/skills/reading/a2-reading'},
    {id:'ge23',en:'Read a simple news story adapted for learners — Breaking News English',pt:'Leia uma notícia simples adaptada para estudantes',cat:'reading',link:'https://breakingnewsenglish.com/level1.html'},
    {id:'ge24',en:'Exercise: Use context clues to guess unknown words',pt:'Exercício: use o contexto para adivinhar palavras novas',cat:'reading',link:'https://learnenglish.britishcouncil.org/skills/reading/a1-reading'},
    {id:'ge25',en:'Write 3 sentences about what you read this week',pt:'Escreva 3 frases sobre o que leu esta semana',cat:'writing',
      variations:{
        beginner:{pt:'Escreva 3 frases simples: do que tratava, quem era o personagem principal e o que você achou',en:'Write 3 simple sentences: what it was about, who the main character was and what you thought'},
        advanced:{pt:'Escreva um parágrafo de 6 frases resumindo o texto e sua opinião pessoal sobre ele',en:'Write a 6-sentence paragraph summarizing the text and sharing your personal opinion about it'},
      }},
  ]},
  { week:6, theme:{en:'Writing Your First Texts',pt:'Escrevendo Seus Primeiros Textos'}, tasks:[
    {id:'ge26',en:'Study: Paragraph structure — topic sentence + support + conclusion',pt:'Estrutura de parágrafo: ideia principal + desenvolvimento + conclusão',cat:'writing',link:'https://learnenglish.britishcouncil.org/skills/writing/a1-writing'},
    {id:'ge27',en:'Exercise: Linking words — and, but, because, so, however',pt:'Exercício: palavras de conexão',cat:'writing',link:'https://learnenglish.britishcouncil.org/grammar/a1-a2/conjunctions'},
    {id:'ge28',en:'Write: A paragraph about your daily routine (80 words)',pt:'Escreva: um parágrafo sobre sua rotina diária (80 palavras)',cat:'writing',
      variations:{
        beginner:{pt:'Escreva 5 frases sobre o que você faz todo dia — hora de acordar, trabalho, refeições e hora de dormir',en:'Write 5 sentences about what you do every day — when you wake up, work, meals and bedtime'},
        advanced:{pt:'Escreva um parágrafo de 100 palavras sobre sua rotina usando Present Simple, advérbios de frequência e conectivos',en:'Write a 100-word paragraph about your routine using Present Simple, frequency adverbs and linking words'},
      }},
    {id:'ge29',en:'Write: An informal message to a friend about your week',pt:'Escreva: uma mensagem informal para um amigo sobre sua semana',cat:'writing',link:'https://learnenglish.britishcouncil.org/skills/writing/a1-writing/informal-messages',
      variations:{
        beginner:{pt:'Escreva uma mensagem curta de 5 frases contando como foi seu dia usando palavras simples',en:'Write a short 5-sentence message telling how your day was using simple words'},
        advanced:{pt:'Escreva uma mensagem informal de 80–100 palavras sobre sua semana usando gírias, contrações e linguagem casual',en:'Write an informal 80–100 word message about your week using slang, contractions and casual language'},
      }},
    {id:'ge30',en:'Exercise: Spelling and punctuation — common mistakes',pt:'Exercício: ortografia',cat:'writing'},
  ]},
]},
  {
    id: 'business', icon: '💼', color: '#5C6F4F',
    en: 'Business English', pt: 'Inglês para Negócios',
    desc: { en: 'Professional communication for the workplace', pt: 'Comunicação profissional para o trabalho' },
    weeks: [
      { week:1, theme:{en:'Professional Introductions',pt:'Apresentações Profissionais'}, tasks:[
        {id:'bj1',en:'Introduce yourself: name, role, company',pt:'Apresentar-se profissionalmente',cat:'speaking',
          variations:{
            beginner:{pt:'Apresente-se em inglês usando frases simples: diga seu nome, profissão e uma coisa que você faz no trabalho',en:'Introduce yourself with simple phrases: say your name, job title and one thing you do at work'},
            advanced:{pt:'Faça uma apresentação profissional completa: trajetória, especialização, conquistas e objetivos (2–3 minutos)',en:'Give a full professional introduction: career path, specialization, achievements and goals (2–3 minutes)'},
          }},
        {id:'bj2',en:'Small talk topics: weather, weekend, commute',pt:'Conversa casual no trabalho',cat:'speaking',
          variations:{
            beginner:{pt:'Aprenda 5 perguntas de conversa casual simples para usar no trabalho',en:'Learn 5 simple small talk questions to use at work'},
            advanced:{pt:'Pratique small talk que vai além do superficial: opiniões, tendências e curiosidades do setor',en:'Practice small talk that goes beyond the surface: opinions, trends and industry curiosities'},
          }},
        {id:'bj3',en:'Business vocabulary: colleague, deadline, meeting',pt:'Vocabulário básico de negócios',cat:'vocab',
          variations:{
            beginner:{pt:'Estude as 20 palavras mais essenciais do ambiente de trabalho em inglês',en:'Study the 20 most essential workplace words in English'},
            advanced:{pt:'Expanda seu vocabulário corporativo com termos de gestão, estratégia e liderança',en:'Expand your corporate vocabulary with management, strategy and leadership terms'},
          }},
        {id:'bj4',en:'Greetings & farewells in professional settings',pt:'Cumprimentos e despedidas profissionais',cat:'speaking'},
        {id:'bj5',en:'Write a professional LinkedIn summary (50 words)',pt:'Resumo profissional em inglês',cat:'writing',
          variations:{
            beginner:{pt:'Escreva 3 frases simples descrevendo sua profissão e o que você gosta de fazer no trabalho',en:'Write 3 simple sentences describing your job and what you enjoy doing at work'},
            advanced:{pt:'Escreva um perfil completo do LinkedIn em inglês: headline, resumo e conquistas (150 palavras)',en:'Write a full LinkedIn profile in English: headline, summary and achievements (150 words)'},
          }},
      ]},
      { week:2, theme:{en:'Email Writing',pt:'Escrita de E-mails'}, tasks:[
        {id:'bj6',en:'Email structure: subject, greeting, body, closing',pt:'Estrutura de e-mail profissional',cat:'writing',
          variations:{
            beginner:{pt:'Conheça a estrutura básica de um e-mail em inglês e copie 3 modelos prontos',en:'Learn the basic structure of an email in English and copy 3 ready-made templates'},
            advanced:{pt:'Analise a estrutura de e-mails executivos e identifique técnicas de persuasão e tom',en:'Analyze executive email structure and identify persuasion techniques and tone'},
          }},
        {id:'bj7',en:'Formal phrases: I am writing to… / Please find attached…',pt:'Frases formais para e-mail',cat:'writing',
          variations:{
            beginner:{pt:'Memorize 8 frases essenciais para abrir e fechar um e-mail formal em inglês',en:'Memorize 8 essential phrases to open and close a formal email in English'},
            advanced:{pt:'Pratique variações sofisticadas de abertura, desenvolvimento e encerramento para diferentes contextos formais',en:'Practice sophisticated opening, body and closing variations for different formal contexts'},
          }},
        {id:'bj8',en:'Polite requests: Could you please… / Would it be possible…',pt:'Pedidos educados por e-mail',cat:'writing'},
        {id:'bj9',en:'Semi-formal emails: Hi vs Dear / Best vs Regards',pt:'E-mails semi-formais',cat:'writing'},
        {id:'bj10',en:'Write 3 emails: request, follow-up, apology',pt:'Escreva 3 e-mails: pedido, follow-up, desculpas',cat:'writing',
          variations:{
            beginner:{pt:'Escreva 1 e-mail simples de pedido usando um modelo como base (mínimo 5 frases)',en:'Write 1 simple request email using a template as a base (minimum 5 sentences)'},
            advanced:{pt:'Escreva os 3 e-mails sem usar modelos prontos, adaptando tom e registro para cada situação',en:'Write all 3 emails without templates, adapting tone and register for each situation'},
          }},
      ]},
      { week:3, theme:{en:'Meetings & Calls',pt:'Reuniões & Videochamadas'}, tasks:[
        {id:'bj11',en:'Meeting vocabulary: agenda, minutes, action item',pt:'Vocabulário de reunião',cat:'vocab',
          variations:{
            beginner:{pt:'Aprenda 10 palavras essenciais de reunião com exemplos de uso em frases reais',en:'Learn 10 essential meeting words with examples of use in real sentences'},
            advanced:{pt:'Estude vocabulário avançado de reunião: action items, minutes, quorum, tabling an issue',en:'Study advanced meeting vocabulary: action items, minutes, quorum, tabling an issue'},
          }},
        {id:'bj12',en:'Chairing a meeting: opening, turn-taking, closing',pt:'Conduzir uma reunião em inglês',cat:'speaking',
          variations:{
            beginner:{pt:'Aprenda as frases básicas para participar de uma reunião: como concordar, discordar e fazer perguntas',en:'Learn basic phrases to participate in a meeting: how to agree, disagree and ask questions'},
            advanced:{pt:'Pratique a condução de reunião do início ao fim: abrir, distribuir a fala, resumir e encerrar',en:'Practice chairing a meeting from start to finish: opening, distributing the floor, summarizing and closing'},
          }},
        {id:'bj13',en:'Interrupting politely: Sorry to interrupt… / If I may add…',pt:'Interromper educadamente',cat:'speaking'},
        {id:'bj14',en:'Video call phrases: Can you hear me? / You are on mute',pt:'Frases para videoconferência',cat:'speaking'},
        {id:'bj15',en:'Roleplay: participate in a 5-minute mock meeting',pt:'Roleplay: reunião simulada de 5 minutos',cat:'speaking',
          variations:{
            beginner:{pt:'Roleplay simples: você participa de uma reunião respondendo perguntas diretas com frases preparadas',en:'Simple roleplay: you join a meeting answering direct questions with prepared phrases'},
            advanced:{pt:'Roleplay completo: você conduz a reunião, distribui a fala, lida com interrupções e chega a uma decisão',en:'Full roleplay: you chair the meeting, manage turns, handle interruptions and reach a decision'},
          }},
      ]},
      { week:4, theme:{en:'Presentations',pt:'Apresentações'}, tasks:[
        {id:'bj16',en:"Opening: Today I'm going to talk about…",pt:'Abrir uma apresentação',cat:'speaking'},
        {id:'bj17',en:'Signposting: First… Moving on… To summarize…',pt:'Linguagem de sinalização',cat:'speaking'},
        {id:'bj18',en:'Describing charts: rise, fall, peak, steady',pt:'Descrever gráficos e tabelas',cat:'vocab'},
        {id:'bj19',en:'Handling questions diplomatically',pt:'Responder perguntas durante apresentação',cat:'speaking'},
        {id:'bj20',en:'Deliver a 3-minute presentation on any topic',pt:'Apresentação de 3 minutos sobre qualquer tema',cat:'speaking'},
      ]},
      { week:5, theme:{en:'Negotiating',pt:'Negociação'}, tasks:[
        {id:'bj21',en:'Negotiation vocabulary: proposal, counter-offer, compromise',pt:'Vocabulário de negociação',cat:'vocab'},
        {id:'bj22',en:"Making proposals: We'd like to suggest… / Our proposal is…",pt:'Fazer propostas em inglês',cat:'speaking'},
        {id:'bj23',en:'Persuasive language: The main advantage… / Evidence shows…',pt:'Linguagem persuasiva',cat:'speaking'},
        {id:'bj24',en:'Reaching agreement: That sounds fair / We can work with that',pt:'Chegar a um acordo',cat:'speaking'},
        {id:'bj25',en:'Write a persuasive business proposal (100 words)',pt:'Proposta de negócios persuasiva',cat:'writing'},
      ]},
      { week:6, theme:{en:'Reports & Data',pt:'Relatórios & Dados'}, tasks:[
        {id:'bj26',en:'Report structure: summary, findings, recommendations',pt:'Estrutura de relatório',cat:'writing'},
        {id:'bj27',en:'Expressing trends: increased by, dropped to, remained stable',pt:'Expressar tendências com dados',cat:'vocab'},
        {id:'bj28',en:'Cause & effect: As a result… / This led to… / Due to…',pt:'Causa e efeito em relatórios',cat:'grammar'},
        {id:'bj29',en:'Passive voice in formal reports: was launched / were analyzed',pt:'Voz passiva em relatórios',cat:'grammar'},
        {id:'bj30',en:'Write a 150-word report based on a chart or scenario',pt:'Relatório de 150 palavras',cat:'writing'},
      ]},
      { week:7, theme:{en:'Business Idioms',pt:'Expressões de Negócios'}, tasks:[
        {id:'bj31',en:'30 essential idioms: touch base, ballpark, bandwidth',pt:'30 expressões idiomáticas de negócios',cat:'vocab'},
        {id:'bj32',en:'Acronyms: ASAP, ETA, KPI, ROI, B2B, B2C',pt:'Siglas comuns no corporativo',cat:'vocab'},
        {id:'bj33',en:'Financial vocabulary: revenue, profit, forecast, budget',pt:'Vocabulário financeiro básico',cat:'vocab'},
        {id:'bj34',en:'HR vocabulary: onboarding, performance review, benefits',pt:'Vocabulário de RH',cat:'vocab'},
        {id:'bj35',en:'Use 10 idioms in a business context paragraph',pt:'Use 10 expressões em um parágrafo',cat:'writing'},
      ]},
      { week:8, theme:{en:'Job Interviews',pt:'Entrevistas de Emprego'}, tasks:[
        {id:'bj36',en:'CV vocabulary: skills, experience, qualifications',pt:'Vocabulário de currículo em inglês',cat:'vocab'},
        {id:'bj37',en:'Interview: Tell me about yourself / Strengths & weaknesses',pt:'Perguntas comuns de entrevista',cat:'speaking'},
        {id:'bj38',en:'STAR method: Situation, Task, Action, Result',pt:'Método STAR para entrevistas',cat:'speaking'},
        {id:'bj39',en:'Asking questions: What does success look like here?',pt:'Perguntar para o entrevistador',cat:'speaking'},
        {id:'bj40',en:'Roleplay: full 10-minute mock interview',pt:'Entrevista simulada completa de 10 minutos',cat:'speaking'},
      ]},
      { week:9, theme:{en:'Networking',pt:'Networking'}, tasks:[
        {id:'bj41',en:'Networking phrases: What do you do? / How did you get into...?',pt:'Frases para networking',cat:'speaking'},
        {id:'bj42',en:'Following up: It was great meeting you…',pt:'Follow-up após eventos',cat:'writing'},
        {id:'bj43',en:'Building rapport: common ground, active listening',pt:'Construir rapport em inglês',cat:'speaking'},
        {id:'bj44',en:'LinkedIn messages: connecting, reaching out, thanking',pt:'Mensagens de LinkedIn',cat:'writing'},
        {id:'bj45',en:'Write a 30-second elevator pitch for yourself',pt:'Elevator pitch de 30 segundos',cat:'speaking'},
      ]},
      { week:10, theme:{en:'Problem Solving',pt:'Solução de Problemas'}, tasks:[
        {id:'bj46',en:'Discussing problems: The issue is… / We are facing a challenge…',pt:'Discutir problemas profissionalmente',cat:'speaking'},
        {id:'bj47',en:'Suggesting solutions: One option would be… / Have you considered…',pt:'Sugerir soluções',cat:'speaking'},
        {id:'bj48',en:'Agreeing & disagreeing diplomatically',pt:'Concordar e discordar diplomaticamente',cat:'speaking'},
        {id:'bj49',en:'Decision vocabulary: pros/cons, trade-off, feasible',pt:'Vocabulário de tomada de decisão',cat:'vocab'},
        {id:'bj50',en:'Case study: analyze a business problem in English',pt:'Estudo de caso em inglês',cat:'speaking'},
      ]},
      { week:11, theme:{en:'Cross-Cultural Communication',pt:'Comunicação Intercultural'}, tasks:[
        {id:'bj51',en:'High vs low-context cultures in business',pt:'Culturas de alto e baixo contexto',cat:'vocab'},
        {id:'bj52',en:'American vs British business English differences',pt:'Inglês americano vs britânico nos negócios',cat:'vocab'},
        {id:'bj53',en:'Tipping, punctuality and etiquette by country',pt:'Gorjeta, pontualidade e etiqueta por país',cat:'vocab'},
        {id:'bj54',en:'Avoiding cultural misunderstandings at work',pt:'Evitar mal-entendidos culturais',cat:'speaking'},
        {id:'bj55',en:'Research a business custom from an English-speaking country',pt:'Pesquisar costume de negócios de país anglófono',cat:'reading'},
      ]},
      { week:12, theme:{en:'Advanced Communication',pt:'Comunicação Avançada'}, tasks:[
        {id:'bj56',en:'Diplomatic language: I appreciate your perspective, however…',pt:'Linguagem diplomática avançada',cat:'speaking'},
        {id:'bj57',en:'Writing executive summaries & memos',pt:'Resumos executivos e memorandos',cat:'writing'},
        {id:'bj58',en:'Crisis communication: addressing problems publicly',pt:'Comunicação em crise',cat:'speaking'},
        {id:'bj59',en:'Understand native business podcasts',pt:'Compreender podcasts de negócios nativos',cat:'listening'},
        {id:'bj60',en:'Final: present a full business proposal to Teacher Renata',pt:'Final: apresentar proposta completa para Teacher Renata',cat:'speaking'},
      ]},
    ]
  },
  {
    id: 'travel', icon: '✈️', color: '#E67A2E',
    en: 'English for Traveling', pt: 'Inglês para Viagens',
    desc: { en: 'Travel confidently anywhere in the world', pt: 'Viaje com confiança a qualquer lugar' },
    weeks: [
      { week:1, theme:{en:'Airport & Check-in',pt:'Aeroporto & Check-in'}, tasks:[
        {id:'tr1',en:'Airport vocabulary: boarding pass, gate, customs, terminal',pt:'Vocabulário de aeroporto',cat:'vocab'},
        {id:'tr2',en:'Check-in dialogue: window or aisle? / luggage to check?',pt:'Diálogo de check-in',cat:'speaking',
          variations:{
            beginner:{pt:'Pratique responder às perguntas básicas do check-in: assento, bagagem e destino com frases curtas',en:'Practice answering basic check-in questions: seat preference, luggage and destination using short phrases'},
            advanced:{pt:'Simule um check-in completo onde você também faz perguntas sobre upgrades, atrasos e serviços do voo',en:'Simulate a full check-in where you also ask questions about upgrades, delays and flight services'},
          }},
        {id:'tr3',en:'Security: remove shoes / place items in the tray',pt:'Frases de segurança no aeroporto',cat:'speaking'},
        {id:'tr4',en:'Understand flight announcements: delays, gate changes',pt:'Entender anúncios de voo',cat:'listening'},
        {id:'tr5',en:'Roleplay the full check-in process',pt:'Roleplay completo do check-in',cat:'speaking',
          variations:{
            beginner:{pt:'Roleplay simples: responda às perguntas do atendente usando as frases que você aprendeu nesta semana',en:'Simple roleplay: answer the agent\'s questions using the phrases you learned this week'},
            advanced:{pt:'Roleplay completo: você faz o check-in, resolve um problema com o assento e pergunta sobre a sala VIP',en:'Full roleplay: you check in, resolve a seating issue and ask about the VIP lounge'},
          }},
      ]},
      { week:2, theme:{en:'Hotels',pt:'Hotéis'}, tasks:[
        {id:'tr6',en:'Hotel vocabulary: reservation, checkout, room service, concierge',pt:'Vocabulário de hotel',cat:'vocab'},
        {id:'tr7',en:'Check-in: I have a reservation / Do you have Wi-Fi?',pt:'Check-in no hotel',cat:'speaking'},
        {id:'tr8',en:'Requests: Could I have extra towels? / Is breakfast included?',pt:'Fazer pedidos no hotel',cat:'speaking',
          variations:{
            beginner:{pt:'Pratique 4 pedidos simples no hotel usando "Could I have…?" e "Is … included?"',en:'Practice 4 simple hotel requests using "Could I have…?" and "Is … included?"'},
            advanced:{pt:'Simule uma conversa com o concierge fazendo pedidos, reclamações e obtendo recomendações de restaurantes',en:'Simulate a conversation with the concierge making requests, a complaint and asking for restaurant recommendations'},
          }},
        {id:'tr9',en:"Complaining: The room is too noisy / The AC isn't working",pt:'Reclamar educadamente no hotel',cat:'speaking'},
        {id:'tr10',en:'Write a hotel review in English (80 words)',pt:'Avaliação de hotel em inglês',cat:'writing',
          variations:{
            beginner:{pt:'Escreva 5 frases sobre um hotel real ou imaginário: o que você gostou e o que não gostou',en:'Write 5 sentences about a real or imaginary hotel: what you liked and what you didn\'t like'},
            advanced:{pt:'Escreva uma avaliação completa de 100 palavras com nota, pontos positivos, negativos e recomendação',en:'Write a full 100-word review with a rating, pros, cons and a recommendation'},
          }},
      ]},
      { week:3, theme:{en:'Transportation',pt:'Transporte'}, tasks:[
        {id:'tr11',en:'Transport vocabulary: subway, fare, platform, transfer',pt:'Vocabulário de transporte',cat:'vocab'},
        {id:'tr12',en:'Buying tickets: single or return? / Which platform?',pt:'Comprar bilhetes de transporte',cat:'speaking',
          variations:{
            beginner:{pt:'Pratique comprar uma passagem simples: destino, tipo (ida ou ida e volta) e plataforma',en:'Practice buying a simple ticket: destination, type (single or return) and platform'},
            advanced:{pt:'Simule a compra de passagens para um grupo, perguntando sobre horários, preços e opções de desconto',en:'Simulate buying tickets for a group, asking about schedules, prices and discount options'},
          }},
        {id:'tr13',en:'Taxi/Uber: Take me to… / How much will that be?',pt:'Pegar táxi ou Uber',cat:'speaking'},
        {id:'tr14',en:'Reading transport maps and signs',pt:'Ler mapas e placas de transporte',cat:'reading'},
        {id:'tr15',en:'Plan a full-day transport itinerary in a foreign city',pt:'Planejar itinerário de transporte',cat:'writing',
          variations:{
            beginner:{pt:'Escreva 4 frases descrevendo como se mover entre 2 pontos turísticos em uma cidade (metrô, ônibus ou a pé)',en:'Write 4 sentences describing how to move between 2 tourist spots in a city (metro, bus or on foot)'},
            advanced:{pt:'Escreva um roteiro detalhado de transporte para um dia completo com horários, linhas e custo estimado',en:'Write a detailed transport itinerary for a full day including schedules, lines and estimated cost'},
          }},
      ]},
      { week:4, theme:{en:'Restaurants',pt:'Restaurantes'}, tasks:[
        {id:'tr16',en:'Restaurant vocabulary: reservation, menu, appetizer, tip',pt:'Vocabulário de restaurante',cat:'vocab'},
        {id:'tr17',en:"Ordering: I'd like… / What do you recommend?",pt:'Pedir comida em inglês',cat:'speaking',
          variations:{
            beginner:{pt:'Pratique pedir 2 pratos e uma bebida usando "I\'d like…" e responder à pergunta "Anything else?"',en:'Practice ordering 2 dishes and a drink using "I\'d like…" and responding to "Anything else?"'},
            advanced:{pt:'Pratique pedir comida, fazer perguntas sobre o menu, pedir alterações no prato e lidar com erros no pedido',en:'Practice ordering food, asking questions about the menu, requesting modifications and dealing with a wrong order'},
          }},
        {id:'tr18',en:"Dietary needs: I'm vegetarian / I'm allergic to nuts",pt:'Expressar restrições alimentares',cat:'speaking'},
        {id:'tr19',en:'Paying: Can we have the check? / Is service included?',pt:'Pagar a conta',cat:'speaking'},
        {id:'tr20',en:'Roleplay a full restaurant experience',pt:'Roleplay completo em restaurante',cat:'speaking',
          variations:{
            beginner:{pt:'Roleplay: entre no restaurante, peça o menu, escolha um prato e pague a conta com frases simples',en:'Roleplay: enter the restaurant, ask for the menu, choose a dish and pay the bill with simple phrases'},
            advanced:{pt:'Roleplay completo: faça reserva, peça com restrições alimentares, reclame de um problema e deixe uma gorjeta',en:'Full roleplay: make a reservation, order with dietary restrictions, complain about an issue and tip appropriately'},
          }},
      ]},
      { week:5, theme:{en:'Shopping',pt:'Compras'}, tasks:[
        {id:'tr21',en:'Shopping vocabulary: receipt, exchange, sale, fitting room',pt:'Vocabulário de compras',cat:'vocab'},
        {id:'tr22',en:'Asking: Do you have this in size…? / How much is this?',pt:'Perguntar sobre produtos',cat:'speaking',
          variations:{
            beginner:{pt:'Pratique 3 perguntas básicas numa loja: tamanho, preço e disponibilidade de cores',en:'Practice 3 basic store questions: size, price and color availability'},
            advanced:{pt:'Simule uma visita à loja perguntando sobre materiais, garantia, desconto e política de troca',en:'Simulate a store visit asking about materials, warranty, discount and exchange policy'},
          }},
        {id:'tr23',en:"Bargaining: That's a bit expensive / Best price?",pt:'Pechinchar em mercados',cat:'speaking'},
        {id:'tr24',en:"Returns: I'd like to return this / It doesn't fit",pt:'Devoluções e trocas',cat:'speaking'},
        {id:'tr25',en:'Souvenir shopping dialogue from start to finish',pt:'Diálogo de compra de souvenirs',cat:'speaking',
          variations:{
            beginner:{pt:'Simule uma compra de souvenir: pergunte o preço, escolha um item e pague',en:'Simulate buying a souvenir: ask the price, choose an item and pay'},
            advanced:{pt:'Simule uma compra completa: compare dois itens, pechinche o preço e peça embrulho para presente',en:'Simulate a full purchase: compare two items, negotiate the price and ask for gift wrapping'},
          }},
      ]},
      { week:6, theme:{en:'Directions',pt:'Direções'}, tasks:[
        {id:'tr26',en:'Direction vocabulary: turn left/right, straight ahead, block',pt:'Vocabulário de direções',cat:'vocab'},
        {id:'tr27',en:'Asking: Excuse me, how do I get to…?',pt:'Pedir direções em inglês',cat:'speaking'},
        {id:'tr28',en:"Understanding: It's on the corner / next to the bank",pt:'Entender direções',cat:'listening'},
        {id:'tr29',en:'Using Google Maps in English',pt:'Usar mapas em inglês',cat:'vocab'},
        {id:'tr30',en:'Give directions from hotel to 3 nearby attractions',pt:'Dar direções para 3 atrações próximas',cat:'speaking',
          variations:{
            beginner:{pt:'Dê direções simples para um lugar próximo usando: vire à esquerda, vire à direita e siga em frente',en:'Give simple directions to one nearby place using: turn left, turn right and go straight ahead'},
            advanced:{pt:'Dê direções detalhadas do hotel para 3 atrações diferentes incluindo pontos de referência e distâncias',en:'Give detailed directions from the hotel to 3 different attractions including landmarks and distances'},
          }},
      ]},
      { week:7, theme:{en:'Medical & Emergencies',pt:'Saúde & Emergências'}, tasks:[
        {id:'tr31',en:'Medical vocabulary: pharmacy, prescription, symptoms, allergy',pt:'Vocabulário médico essencial',cat:'vocab'},
        {id:'tr32',en:'Pharmacy: I have a headache / I need something for…',pt:'Na farmácia em inglês',cat:'speaking'},
        {id:'tr33',en:'Emergency phrases: Call an ambulance! / I need help!',pt:'Frases de emergência',cat:'speaking'},
        {id:'tr34',en:'Describe symptoms: sharp pain, swelling, fever, dizziness',pt:'Descrever sintomas claramente',cat:'speaking'},
        {id:'tr35',en:'Emergency services: 911 in the US / 999 in the UK',pt:'Serviços de emergência por país',cat:'vocab'},
      ]},
      { week:8, theme:{en:'Sightseeing',pt:'Turismo'}, tasks:[
        {id:'tr36',en:'Tourism vocabulary: landmark, tour guide, admission, souvenir',pt:'Vocabulário de turismo',cat:'vocab'},
        {id:'tr37',en:'Tickets: Do you have student discounts? / What time does it close?',pt:'Comprar ingressos para atrações',cat:'speaking'},
        {id:'tr38',en:'Describing places: magnificent, breathtaking, overrated',pt:'Descrever lugares em inglês',cat:'vocab'},
        {id:'tr39',en:'Photos: Would you mind taking a photo of us?',pt:'Pedir para tirar fotos',cat:'speaking'},
        {id:'tr40',en:'Write a travel journal entry about a tourist spot',pt:'Diário de viagem sobre uma atração',cat:'writing'},
      ]},
      { week:9, theme:{en:'Reservations',pt:'Reservas'}, tasks:[
        {id:'tr41',en:'Reservation vocabulary: availability, deposit, cancellation policy',pt:'Vocabulário de reservas',cat:'vocab'},
        {id:'tr42',en:"Restaurant: Table for 2 at 8pm / Any dietary needs?",pt:'Reservas de restaurante',cat:'speaking'},
        {id:'tr43',en:"Hotel by phone: I'd like to book a room for…",pt:'Reservas de hotel por telefone',cat:'speaking'},
        {id:'tr44',en:'Changing/canceling: I need to change / cancel my booking',pt:'Modificar e cancelar reservas',cat:'speaking'},
        {id:'tr45',en:'Write a booking confirmation email',pt:'E-mail de confirmação de reserva',cat:'writing'},
      ]},
      { week:10, theme:{en:'Cultural Etiquette',pt:'Etiqueta Cultural'}, tasks:[
        {id:'tr46',en:'Greetings: handshakes, hugs, cheek kisses by culture',pt:'Cumprimentos em diferentes culturas',cat:'vocab'},
        {id:'tr47',en:'Table manners in English-speaking countries',pt:'Etiqueta à mesa',cat:'vocab'},
        {id:'tr48',en:'Tipping: when, how much, and how to do it',pt:'Cultura de gorjeta',cat:'vocab'},
        {id:'tr49',en:"Social dos and don'ts: US, UK, Australia",pt:'O que fazer e evitar em países anglófonos',cat:'vocab'},
        {id:'tr50',en:'Research cultural facts about one English-speaking country',pt:'Curiosidades culturais de um país anglófono',cat:'reading'},
      ]},
      { week:11, theme:{en:'Travel Problems',pt:'Problemas de Viagem'}, tasks:[
        {id:'tr51',en:'Lost luggage: My bag is missing / Can you check?',pt:'Bagagem perdida',cat:'speaking'},
        {id:'tr52',en:'Delays: compensation, vouchers, rebooking',pt:'Atrasos e cancelamentos de voo',cat:'speaking'},
        {id:'tr53',en:"Formal complaints: I'd like to speak to the manager",pt:'Fazer reclamações formais',cat:'speaking'},
        {id:'tr54',en:'Filling complaint forms in English',pt:'Preencher formulários de reclamação',cat:'writing'},
        {id:'tr55',en:'Write a complaint email to an airline or hotel',pt:'E-mail de reclamação para companhia aérea',cat:'writing'},
      ]},
      { week:12, theme:{en:'Connecting with Locals',pt:'Conectar-se com Locais'}, tasks:[
        {id:'tr56',en:"Conversation starters: Where are you from? / What's this area like?",pt:'Iniciar conversa com desconhecidos',cat:'speaking'},
        {id:'tr57',en:'Talking about Brazil: culture, food, weather, sports',pt:'Falar sobre o Brasil para estrangeiros',cat:'speaking'},
        {id:'tr58',en:'Understanding accents: American, British, Australian',pt:'Entender sotaques regionais',cat:'listening'},
        {id:'tr59',en:'Social media in English: caption, hashtag, DM, story',pt:'Redes sociais em inglês',cat:'vocab'},
        {id:'tr60',en:'Prepare a 2-minute travel story to share with Teacher Renata',pt:'História de viagem para compartilhar',cat:'speaking'},
      ]},
    ]
  },
  {
    id: 'conversation', icon: '💬', color: '#C97080',
    en: 'Conversation Focus', pt: 'Foco em Conversação',
    desc: { en: 'Build real fluency through guided conversation', pt: 'Desenvolva fluência real através de conversação guiada' },
    weeks: [
      { week:1, theme:{en:'Breaking the Ice',pt:'Quebrando o Gelo'}, tasks:[
        {id:'cv1',en:'Small talk topics: weather, news, sports, weekend plans',pt:'Temas de conversa casual',cat:'speaking'},
        {id:'cv2',en:'Follow-up questions to keep conversation going',pt:'Perguntas de follow-up para manter a conversa',cat:'speaking'},
        {id:'cv3',en:"Active listening: Really? That's interesting! / Tell me more",pt:'Frases de escuta ativa',cat:'speaking'},
        {id:'cv4',en:'Avoiding awkward silences: polite fillers',pt:'Evitar silêncios desconfortáveis',cat:'speaking'},
        {id:'cv5',en:'5-minute recorded conversation on a fun topic',pt:'Conversa gravada de 5 minutos',cat:'speaking'},
      ]},
      { week:2, theme:{en:'Expressing Opinions',pt:'Expressando Opiniões'}, tasks:[
        {id:'cv6',en:'Opinion phrases: I think… / In my opinion… / It seems to me…',pt:'Frases de opinião',cat:'speaking'},
        {id:'cv7',en:"Agreeing: Absolutely! / That's a good point / Exactly!",pt:'Concordar em inglês',cat:'speaking'},
        {id:'cv8',en:'Disagreeing politely: I see your point, but…',pt:'Discordar educadamente',cat:'speaking'},
        {id:'cv9',en:"Hedging: It might be… / I'm not 100% sure, but…",pt:'Falar com cautela sobre opiniões',cat:'speaking'},
        {id:'cv10',en:'Discussion on a topic you feel strongly about',pt:'Discussão sobre tema que você defende',cat:'speaking'},
      ]},
      { week:3, theme:{en:'Storytelling',pt:'Contar Histórias'}, tasks:[
        {id:'cv11',en:'Narrative tenses: Past simple, Past continuous, Past perfect',pt:'Tempos narrativos em inglês',cat:'grammar'},
        {id:'cv12',en:"Story openers: So there I was… / You won't believe what happened…",pt:'Como começar uma história',cat:'speaking'},
        {id:'cv13',en:'Building suspense: And then… / Suddenly… / Just as…',pt:'Criar suspense ao contar histórias',cat:'speaking'},
        {id:'cv14',en:'Emotion words: shocked, relieved, embarrassed, thrilled',pt:'Descrever emoções em narrativa',cat:'vocab'},
        {id:'cv15',en:'Tell a funny or memorable personal story (3 minutes)',pt:'Contar uma história pessoal engraçada',cat:'speaking'},
      ]},
      { week:4, theme:{en:'Debating',pt:'Debatendo'}, tasks:[
        {id:'cv16',en:'Debate structure: thesis, argument, counter, conclusion',pt:'Estrutura de debate',cat:'speaking'},
        {id:'cv17',en:'Introducing arguments: The main point is… / First and foremost…',pt:'Introduzir argumentos',cat:'speaking'},
        {id:'cv18',en:'Countering: While I agree… / On the other hand…',pt:'Rebater argumentos',cat:'speaking'},
        {id:'cv19',en:'Hot topics: technology, social media, environment',pt:'Temas quentes para debate',cat:'speaking'},
        {id:'cv20',en:'Mini-debate on a topic of your choice (5 minutes)',pt:'Mini-debate de 5 minutos',cat:'speaking'},
      ]},
      { week:5, theme:{en:'Humor & Irony',pt:'Humor & Ironia'}, tasks:[
        {id:'cv21',en:'British vs American humor: subtle vs direct',pt:'Humor britânico vs americano',cat:'vocab'},
        {id:'cv22',en:'Understanding irony and sarcasm in context',pt:'Entender ironia e sarcasmo',cat:'listening'},
        {id:'cv23',en:'Wordplay and puns: why they work in English',pt:'Trocadilhos e jogos de palavras',cat:'vocab'},
        {id:'cv24',en:'Appropriate moments for humor',pt:'Momentos apropriados para o humor',cat:'speaking'},
        {id:'cv25',en:'Watch and discuss a stand-up comedy clip',pt:'Assistir e discutir stand-up comedy',cat:'listening'},
      ]},
      { week:6, theme:{en:'Phone & Video Calls',pt:'Ligações & Videochamadas'}, tasks:[
        {id:'cv26',en:"Phone phrases: Speaking! / Could you hold? / I'll transfer you",pt:'Frases para ligações',cat:'speaking'},
        {id:'cv27',en:'Leaving voicemail: Hi, this is… Please call back at…',pt:'Deixar mensagem de voz',cat:'speaking'},
        {id:'cv28',en:'Clarifying: Sorry, could you repeat that? / Did you say…?',pt:'Pedir esclarecimentos em ligações',cat:'speaking'},
        {id:'cv29',en:'Video call etiquette: mute, background, turn-taking',pt:'Etiqueta em videochamadas',cat:'speaking'},
        {id:'cv30',en:'Roleplay: professional phone call in English',pt:'Roleplay: ligação profissional',cat:'speaking'},
      ]},
      { week:7, theme:{en:'Social Situations',pt:'Situações Sociais'}, tasks:[
        {id:'cv31',en:'Party vocabulary: invite, toast, mingle, plus-one',pt:'Linguagem de festas e eventos',cat:'vocab'},
        {id:'cv32',en:'Meeting people: What do you do? / How do you know the host?',pt:'Conhecer pessoas em eventos',cat:'speaking'},
        {id:'cv33',en:"Compliments: I love your… / That's so kind of you!",pt:'Dar e receber elogios',cat:'speaking'},
        {id:'cv34',en:'Leaving conversations: It was lovely chatting / I should go…',pt:'Encerrar conversas educadamente',cat:'speaking'},
        {id:'cv35',en:'Simulate a dinner party conversation',pt:'Simular uma conversa em jantar social',cat:'speaking'},
      ]},
      { week:8, theme:{en:'Culture & Lifestyle',pt:'Cultura & Estilo de Vida'}, tasks:[
        {id:'cv36',en:"Hobbies: I'm into… / I've been really enjoying…",pt:'Falar sobre hobbies',cat:'speaking'},
        {id:'cv37',en:'Food culture: favorite dishes, dietary trends',pt:'Cultura alimentar',cat:'speaking'},
        {id:'cv38',en:'Entertainment: movies, music, podcasts, books',pt:'Entretenimento em inglês',cat:'speaking'},
        {id:'cv39',en:'Comparing Brazilian and English-speaking cultures',pt:'Comparar cultura brasileira com anglófonas',cat:'speaking'},
        {id:'cv40',en:'Present your favorite Brazilian thing to an English speaker',pt:'Apresentar algo favorito do Brasil',cat:'speaking'},
      ]},
      { week:9, theme:{en:'Emotional Expression',pt:'Expressar Emoções'}, tasks:[
        {id:'cv41',en:'Advanced emotions: elated, devastated, uneasy, bewildered',pt:'Vocabulário emocional avançado',cat:'vocab'},
        {id:'cv42',en:'Empathy: That must be hard / I totally understand',pt:'Expressar empatia',cat:'speaking'},
        {id:'cv43',en:'Sharing feelings: I feel… / It makes me… / I get emotional when…',pt:'Compartilhar sentimentos',cat:'speaking'},
        {id:'cv44',en:"Comforting: Everything will be okay / I'm here for you",pt:'Consolar alguém em inglês',cat:'speaking'},
        {id:'cv45',en:'Discuss a meaningful life experience in English',pt:'Discutir experiência de vida significativa',cat:'speaking'},
      ]},
      { week:10, theme:{en:'Register & Tone',pt:'Registro & Tom'}, tasks:[
        {id:'cv46',en:'Formal vs informal: meetings vs close friends',pt:'Formal vs informal em conversação',cat:'vocab'},
        {id:'cv47',en:'Casual English: slang, contractions, fillers (like, you know)',pt:'Inglês casual e gírias',cat:'vocab'},
        {id:'cv48',en:'Same message in 3 different registers',pt:'Mesma mensagem em 3 registros diferentes',cat:'speaking'},
        {id:'cv49',en:'Reading the room: formal, casual or playful?',pt:'Ler a situação e adaptar o registro',cat:'speaking'},
        {id:'cv50',en:'Switch between formal and informal in practice',pt:'Praticar alternância entre formal e informal',cat:'speaking'},
      ]},
      { week:11, theme:{en:'Fluency Strategies',pt:'Estratégias de Fluência'}, tasks:[
        {id:'cv51',en:'Fillers: Well… / Let me think… / Actually… / You know…',pt:'Preenchedores de fala natural',cat:'speaking'},
        {id:'cv52',en:"Paraphrasing: What I mean is… / In other words… / It's like…",pt:'Parafrasear quando não sabe a palavra',cat:'speaking'},
        {id:'cv53',en:'Self-correction: Well, I meant to say… / Actually…',pt:'Autocorrigir-se naturalmente',cat:'speaking'},
        {id:'cv54',en:"Circumlocution: describe words you don't know",pt:'Descrever o que não sabe dizer',cat:'speaking'},
        {id:'cv55',en:'Record yourself speaking for 5 minutes non-stop',pt:'Gravar-se por 5 minutos sem parar',cat:'speaking'},
      ]},
      { week:12, theme:{en:'Natural Speech',pt:'Fala Natural'}, tasks:[
        {id:'cv56',en:'Connected speech: linking, reduction (wanna, gonna, kinda)',pt:'Fala conectada em inglês natural',cat:'pronunciation'},
        {id:'cv57',en:'Intonation for meaning: questions, surprise, sarcasm',pt:'Entonação para transmitir significado',cat:'pronunciation'},
        {id:'cv58',en:'Rhythm and stress in English sentences',pt:'Ritmo e ênfase em frases',cat:'pronunciation'},
        {id:'cv59',en:"Shadow a native speaker's delivery exactly",pt:'Imitar um falante nativo exatamente',cat:'listening'},
        {id:'cv60',en:'Final: 10-minute free conversation with Teacher Renata',pt:'Final: conversa livre de 10 minutos',cat:'speaking'},
      ]},
    ]
  },
  {
    id: 'grammar', icon: '🔧', color: '#8A3F2C',
    en: 'Grammar Repair Kit', pt: 'Gramática na Prática',
    desc: { en: 'Fix grammar gaps and build rock-solid foundations', pt: 'Corrija lacunas gramaticais e construa bases sólidas' },
    weeks: [
      { week:1, theme:{en:'Articles: A, An, The',pt:'Artigos: A, An, The'}, tasks:[
        {id:'gr1',en:'A vs An: vowel sounds, not letters (an hour, a university)',pt:'A vs An: sons de vogais, não letras',cat:'grammar'},
        {id:'gr2',en:'The vs no article: the sun, love, countries',pt:'The vs sem artigo: sol, amor, países',cat:'grammar'},
        {id:'gr3',en:'Generic reference: Dogs are friendly (not The dogs)',pt:'Referência genérica com artigos',cat:'grammar'},
        {id:'gr4',en:'Articles with professions, places and institutions',pt:'Artigos com profissões, lugares e instituições',cat:'grammar'},
        {id:'gr5',en:'Error correction: fix 15 article mistakes in a text',pt:'Corrija 15 erros de artigos',cat:'grammar'},
      ]},
      { week:2, theme:{en:'Prepositions',pt:'Preposições'}, tasks:[
        {id:'gr6',en:'In, on, at for time: in the morning, on Monday, at 3pm',pt:'In, on, at para tempo',cat:'grammar'},
        {id:'gr7',en:'In, on, at for place: in Brazil, on the table, at the door',pt:'In, on, at para lugar',cat:'grammar'},
        {id:'gr8',en:'Movement: to, into, through, across, along',pt:'Preposições de movimento',cat:'grammar'},
        {id:'gr9',en:'Verb + preposition: depend on, look forward to, deal with',pt:'Verbos + preposições fixas',cat:'grammar'},
        {id:'gr10',en:'Write a paragraph using at least 10 different prepositions',pt:'Parágrafo com 10 preposições diferentes',cat:'writing'},
      ]},
      { week:3, theme:{en:'Present Tenses',pt:'Tempos do Presente'}, tasks:[
        {id:'gr11',en:'Simple Present vs Present Continuous: live vs am living',pt:'Simple vs Continuous no presente',cat:'grammar'},
        {id:'gr12',en:'State verbs: know, believe, understand, love (no -ing!)',pt:'Verbos de estado sem -ing',cat:'grammar'},
        {id:'gr13',en:'Present Perfect vs Simple Past: I have been / I was',pt:'Present Perfect vs Simple Past',cat:'grammar'},
        {id:'gr14',en:'Present Perfect Continuous: I have been studying for 2 hours',pt:'Present Perfect Continuous',cat:'grammar'},
        {id:'gr15',en:'Write about your typical day using all present tenses',pt:'Escreva sobre seu dia usando todos os presentes',cat:'writing'},
      ]},
      { week:4, theme:{en:'Past Tenses',pt:'Tempos do Passado'}, tasks:[
        {id:'gr16',en:'Simple Past vs Past Continuous: I ate / I was eating',pt:'Simple Past vs Past Continuous',cat:'grammar'},
        {id:'gr17',en:'Past Perfect: I had already eaten when she arrived',pt:'Past Perfect: antes de outra ação no passado',cat:'grammar'},
        {id:'gr18',en:'Used to: I used to play football (no longer true)',pt:'Used to: hábitos do passado',cat:'grammar'},
        {id:'gr19',en:'Would for past habits: Every summer we would go to the beach',pt:'Would para hábitos passados',cat:'grammar'},
        {id:'gr20',en:'Write a story using all past tenses in context',pt:'História usando todos os passados',cat:'writing'},
      ]},
      { week:5, theme:{en:'Future Forms',pt:'Formas do Futuro'}, tasks:[
        {id:'gr21',en:'Will vs going to: spontaneous vs planned',pt:'Will vs going to: espontâneo vs planejado',cat:'grammar'},
        {id:'gr22',en:"Present Continuous for future: I'm meeting her tonight",pt:'Present Continuous para futuro próximo',cat:'grammar'},
        {id:'gr23',en:'Future Perfect: By 2030, I will have learned English',pt:'Future Perfect',cat:'grammar'},
        {id:'gr24',en:'Future Continuous: This time next year I will be traveling',pt:'Future Continuous',cat:'grammar'},
        {id:'gr25',en:'Write about plans and predictions for the next 5 years',pt:'Planos e previsões para os próximos 5 anos',cat:'writing'},
      ]},
      { week:6, theme:{en:'Modal Verbs',pt:'Verbos Modais'}, tasks:[
        {id:'gr26',en:'Can / Could / Be able to: ability past, present, future',pt:'Can / Could / Be able to: habilidade',cat:'grammar'},
        {id:'gr27',en:'Should / Ought to / Had better: advice',pt:'Should / Had better: conselho',cat:'grammar'},
        {id:'gr28',en:'Must / Have to / Need to: obligation and necessity',pt:'Must / Have to: obrigação',cat:'grammar'},
        {id:'gr29',en:'May / Might / Could: possibility and permission',pt:'May / Might: possibilidade',cat:'grammar'},
        {id:'gr30',en:'20 modal sentences using different functions',pt:'20 frases com modais diferentes',cat:'grammar'},
      ]},
      { week:7, theme:{en:'Conditionals',pt:'Condicionais'}, tasks:[
        {id:'gr31',en:'Zero Conditional: If you heat ice, it melts',pt:'Zero Conditional para fatos',cat:'grammar'},
        {id:'gr32',en:"First Conditional: If it rains, I'll stay home",pt:'First Conditional: possibilidades reais',cat:'grammar'},
        {id:'gr33',en:'Second Conditional: If I were rich, I would travel',pt:'Second Conditional: situações imaginárias',cat:'grammar'},
        {id:'gr34',en:'Third Conditional: If I had studied, I would have passed',pt:'Third Conditional: arrependimentos',cat:'grammar'},
        {id:'gr35',en:'Write one example of each conditional about your own life',pt:'Um exemplo de cada condicional sobre sua vida',cat:'writing'},
      ]},
      { week:8, theme:{en:'Passive Voice',pt:'Voz Passiva'}, tasks:[
        {id:'gr36',en:'Passive structure: be + past participle',pt:'Estrutura da voz passiva',cat:'grammar'},
        {id:'gr37',en:'When to use passive: unknown agent, formal writing',pt:'Quando usar voz passiva',cat:'grammar'},
        {id:'gr38',en:'Passive in different tenses: is made, was made, has been made',pt:'Passiva em diferentes tempos verbais',cat:'grammar'},
        {id:'gr39',en:'Passive with modals: can be done, should be fixed',pt:'Passiva com modais',cat:'grammar'},
        {id:'gr40',en:'Rewrite 10 active sentences in the passive voice',pt:'Reescreva 10 frases na voz passiva',cat:'grammar'},
      ]},
      { week:9, theme:{en:'Relative Clauses',pt:'Orações Relativas'}, tasks:[
        {id:'gr41',en:'Who, which, that: choosing the right pronoun',pt:'Who, which, that: escolher o pronome',cat:'grammar'},
        {id:'gr42',en:'Defining vs non-defining (with commas)',pt:'Orações relativas definidoras vs não-definidoras',cat:'grammar'},
        {id:'gr43',en:'Where, when, whose in relative clauses',pt:'Where, when, whose em orações relativas',cat:'grammar'},
        {id:'gr44',en:'Reduced relative clauses: the man sitting (who is sitting)',pt:'Orações relativas reduzidas',cat:'grammar'},
        {id:'gr45',en:'Write 10 sentences with different relative clauses',pt:'10 frases com orações relativas diferentes',cat:'writing'},
      ]},
      { week:10, theme:{en:'Common Mistakes',pt:'Erros Comuns'}, tasks:[
        {id:'gr46',en:'Brazilian errors: make vs do, say vs tell, bring vs take',pt:'Erros comuns de brasileiros',cat:'grammar'},
        {id:'gr47',en:'Countable & uncountable: much/many, few/little',pt:'Contáveis e incontáveis',cat:'grammar'},
        {id:'gr48',en:"False friends: actually, eventually, pretend, realize",pt:'Falsos cognatos mais comuns',cat:'vocab'},
        {id:'gr49',en:"Confusing words: affect/effect, their/there/they're",pt:'Palavras confusas em inglês',cat:'grammar'},
        {id:'gr50',en:'Find and fix 20 common grammar mistakes in a text',pt:'Encontre e corrija 20 erros gramaticais',cat:'grammar'},
      ]},
      { week:11, theme:{en:'Gerunds & Infinitives',pt:'Gerúndios & Infinitivos'}, tasks:[
        {id:'gr51',en:'Gerund as subject: Swimming is good for you',pt:'Gerúndio como sujeito',cat:'grammar'},
        {id:'gr52',en:'Verbs + gerund: enjoy, avoid, suggest, keep, finish',pt:'Verbos seguidos de gerúndio',cat:'grammar'},
        {id:'gr53',en:'Verbs + infinitive: want, decide, hope, plan, refuse',pt:'Verbos seguidos de infinitivo',cat:'grammar'},
        {id:'gr54',en:'Both forms, different meaning: stop, try, remember, forget',pt:'Verbos que mudam de sentido',cat:'grammar'},
        {id:'gr55',en:'Write 20 sentences using gerunds and infinitives correctly',pt:'20 frases com gerúndios e infinitivos',cat:'grammar'},
      ]},
      { week:12, theme:{en:'Advanced Structures',pt:'Estruturas Avançadas'}, tasks:[
        {id:'gr56',en:'Inversion for emphasis: Never have I seen… / Rarely do I…',pt:'Inversão para ênfase',cat:'grammar'},
        {id:'gr57',en:'Cleft sentences: It was the price that surprised me',pt:'Frases clivadas',cat:'grammar'},
        {id:'gr58',en:'Participle clauses: Having finished work, she went home',pt:'Orações participiais',cat:'grammar'},
        {id:'gr59',en:'Review your biggest grammar challenges from this journey',pt:'Revisar seus maiores desafios gramaticais',cat:'grammar'},
        {id:'gr60',en:'Final: write a 200-word text with zero grammar errors',pt:'Final: texto de 200 palavras sem erros',cat:'writing'},
      ]},
    ]
  },
  {
    id: 'academic', icon: '📝', color: '#2D5016',
    en: 'Academic & Professional Writing', pt: 'Escrita Acadêmica',
    desc: { en: 'Master formal writing for academic and professional contexts', pt: 'Domine a escrita formal e acadêmica' },
    weeks: [
      { week:1, theme:{en:'Paragraph Structure',pt:'Estrutura de Parágrafos'}, tasks:[
        {id:'ac1',en:'Topic sentence: one clear main idea per paragraph',pt:'Frase tópica: uma ideia por parágrafo',cat:'writing'},
        {id:'ac2',en:'Supporting sentences: evidence, examples, explanation',pt:'Frases de apoio: evidência, exemplos',cat:'writing'},
        {id:'ac3',en:'Concluding sentence: summarize or link forward',pt:'Frase de conclusão do parágrafo',cat:'writing'},
        {id:'ac4',en:'Unity & coherence: staying on topic',pt:'Unidade e coerência no parágrafo',cat:'writing'},
        {id:'ac5',en:'Write 2 well-structured paragraphs on any topic',pt:'Escreva 2 parágrafos bem estruturados',cat:'writing'},
      ]},
      { week:2, theme:{en:'Linking Words',pt:'Conectivos'}, tasks:[
        {id:'ac6',en:'Addition: furthermore, moreover, in addition, also',pt:'Adição: furthermore, moreover',cat:'grammar'},
        {id:'ac7',en:'Contrast: however, although, while, on the other hand',pt:'Contraste: however, although',cat:'grammar'},
        {id:'ac8',en:'Cause & effect: therefore, as a result, consequently',pt:'Causa e efeito: therefore, as a result',cat:'grammar'},
        {id:'ac9',en:'Illustration: for example, such as, for instance',pt:'Exemplificação: for example, such as',cat:'grammar'},
        {id:'ac10',en:'Write a paragraph using at least 6 different linking words',pt:'Parágrafo com 6 conectivos diferentes',cat:'writing'},
      ]},
      { week:3, theme:{en:'Essay Writing',pt:'Redação Dissertativa'}, tasks:[
        {id:'ac11',en:'Essay structure: introduction, body paragraphs, conclusion',pt:'Estrutura: introdução, desenvolvimento, conclusão',cat:'writing'},
        {id:'ac12',en:'Writing a strong thesis statement',pt:'Escrever uma tese forte',cat:'writing'},
        {id:'ac13',en:'Introduction: hook, background, thesis',pt:'Introdução: gancho, contexto, tese',cat:'writing'},
        {id:'ac14',en:'Conclusion: restate, reflect, call to action',pt:'Técnicas de conclusão',cat:'writing'},
        {id:'ac15',en:'Write a 200-word opinion essay with proper structure',pt:'Redação de 200 palavras com estrutura correta',cat:'writing'},
      ]},
      { week:4, theme:{en:'Academic Vocabulary',pt:'Vocabulário Acadêmico'}, tasks:[
        {id:'ac16',en:'Academic Word List: analyze, evaluate, identify, require',pt:'Lista acadêmica: analyze, evaluate, identify',cat:'vocab'},
        {id:'ac17',en:'Formal vs informal: use vs utilize, start vs commence',pt:'Vocabulário formal vs informal',cat:'vocab'},
        {id:'ac18',en:'Hedging: it appears that / this may suggest / arguably',pt:'Linguagem de atenuação acadêmica',cat:'vocab'},
        {id:'ac19',en:'Reporting verbs: argues, claims, suggests, demonstrates',pt:'Verbos de citação e relato',cat:'vocab'},
        {id:'ac20',en:'Replace informal words with formal equivalents in a text',pt:'Substituir palavras informais por formais',cat:'writing'},
      ]},
      { week:5, theme:{en:'Formal Emails',pt:'E-mails Formais'}, tasks:[
        {id:'ac21',en:'Email conventions: subject, salutation, body, sign-off',pt:'Convenções de e-mail formal',cat:'writing'},
        {id:'ac22',en:'Openings: I am writing to enquire about / with reference to',pt:'Linhas de abertura formais',cat:'writing'},
        {id:'ac23',en:'Polite requests in formal register',pt:'Pedidos educados no registro formal',cat:'writing'},
        {id:'ac24',en:'Closings: Yours sincerely / faithfully / Best regards',pt:'Encerramentos formais',cat:'writing'},
        {id:'ac25',en:'Write 3 emails: inquiry, application, complaint',pt:'3 e-mails: consulta, candidatura, reclamação',cat:'writing'},
      ]},
      { week:6, theme:{en:'Reports & Proposals',pt:'Relatórios & Propostas'}, tasks:[
        {id:'ac26',en:'Report structure: title, introduction, findings, conclusion',pt:'Estrutura de relatório formal',cat:'writing'},
        {id:'ac27',en:'Objective language: avoid I / use passive forms',pt:'Linguagem objetiva: evitar I, usar passiva',cat:'writing'},
        {id:'ac28',en:'Describing findings: approximately, roughly, precisely',pt:'Descrever resultados com dados',cat:'writing'},
        {id:'ac29',en:'Recommendations: It is recommended that… / We suggest…',pt:'Fazer recomendações formais',cat:'writing'},
        {id:'ac30',en:'Write a 200-word report on a topic of your choice',pt:'Relatório de 200 palavras',cat:'writing'},
      ]},
      { week:7, theme:{en:'Argumentation',pt:'Argumentação'}, tasks:[
        {id:'ac31',en:'Types of arguments: fact, opinion, evidence, example',pt:'Tipos de argumentos',cat:'writing'},
        {id:'ac32',en:'Counterarguments: acknowledge and refute opposing views',pt:'Contra-argumentos: reconhecer e refutar',cat:'writing'},
        {id:'ac33',en:'Logical fallacies to avoid: generalization, false cause',pt:'Falácias lógicas a evitar',cat:'writing'},
        {id:'ac34',en:'Evaluating sources: credibility, bias, relevance',pt:'Avaliar fontes: credibilidade e viés',cat:'reading'},
        {id:'ac35',en:'Write an argumentative paragraph with evidence and counter',pt:'Parágrafo argumentativo com evidência e contra',cat:'writing'},
      ]},
      { week:8, theme:{en:'Summarizing & Paraphrasing',pt:'Resumir & Parafrasear'}, tasks:[
        {id:'ac36',en:'Summarize: main ideas only, shorter than original',pt:'Resumir: apenas ideias principais',cat:'writing'},
        {id:'ac37',en:'Paraphrase: change words AND structure, not just synonyms',pt:'Parafrasear: mudar palavras E estrutura',cat:'writing'},
        {id:'ac38',en:'Quoting and citing sources properly',pt:'Citar fontes na escrita acadêmica',cat:'writing'},
        {id:'ac39',en:'Avoiding plagiarism: attribution techniques',pt:'Evitar plágio',cat:'writing'},
        {id:'ac40',en:'Summarize and paraphrase a 200-word article',pt:'Resumir e parafrasear um artigo',cat:'writing'},
      ]},
      { week:9, theme:{en:'Research Writing',pt:'Escrita de Pesquisa'}, tasks:[
        {id:'ac41',en:'Literature review: synthesize, compare, contrast sources',pt:'Revisão de literatura: sintetizar fontes',cat:'writing'},
        {id:'ac42',en:'Academic transitions between sources',pt:'Transições acadêmicas entre fontes',cat:'writing'},
        {id:'ac43',en:'Methodology sections: method, participant, procedure',pt:'Seção de metodologia',cat:'writing'},
        {id:'ac44',en:'Discussion sections: interpret, analyze, compare',pt:'Seção de discussão',cat:'writing'},
        {id:'ac45',en:'Write a 3-paragraph mini research paper',pt:'Mini artigo de pesquisa de 3 parágrafos',cat:'writing'},
      ]},
      { week:10, theme:{en:'Punctuation & Editing',pt:'Pontuação & Revisão'}, tasks:[
        {id:'ac46',en:'Commas: lists, clauses, appositives, introductory phrases',pt:'Vírgulas: listas, orações, aposições',cat:'grammar'},
        {id:'ac47',en:'Semicolons and colons: when and how',pt:'Ponto e vírgula e dois pontos',cat:'grammar'},
        {id:'ac48',en:"Apostrophes: possession and contractions",pt:'Apóstrofos: posse e contrações',cat:'grammar'},
        {id:'ac49',en:'Editing checklist: grammar, clarity, coherence, style',pt:'Lista de revisão de texto',cat:'writing'},
        {id:'ac50',en:'Proofread and edit a piece of your own writing',pt:'Revisar e editar um texto próprio',cat:'writing'},
      ]},
      { week:11, theme:{en:'Professional Documents',pt:'Documentos Profissionais'}, tasks:[
        {id:'ac51',en:'Cover letters: structure, tone, tailoring to the job',pt:'Cartas de apresentação',cat:'writing'},
        {id:'ac52',en:'CV in English: format, action verbs, keywords',pt:'CV em inglês: formato e verbos de ação',cat:'writing'},
        {id:'ac53',en:'Executive summaries: 1 page, key points only',pt:'Resumos executivos',cat:'writing'},
        {id:'ac54',en:'Memos and business letters: format and register',pt:'Memorandos e cartas comerciais',cat:'writing'},
        {id:'ac55',en:'Write a cover letter for a job you would actually want',pt:'Carta de apresentação para emprego real',cat:'writing'},
      ]},
      { week:12, theme:{en:'Final Portfolio',pt:'Portfólio Final'}, tasks:[
        {id:'ac56',en:'Revise your best writing piece from this journey',pt:'Revisar seu melhor texto desta jornada',cat:'writing'},
        {id:'ac57',en:'Write a 350-word argumentative essay (exam-level)',pt:'Redação argumentativa de 350 palavras',cat:'writing'},
        {id:'ac58',en:'Self-evaluate: what type of writing improved most?',pt:'Autoavaliar: qual escrita melhorou mais?',cat:'writing'},
        {id:'ac59',en:'Exchange texts and give written feedback to a peer',pt:'Trocar textos e dar feedback escrito',cat:'writing'},
        {id:'ac60',en:'Present your portfolio to Teacher Renata',pt:'Apresentar portfólio para Teacher Renata',cat:'speaking'},
      ]},
    ]
  },
  {
    id: 'popculture', icon: '🎬', color: '#E67A2E',
    en: 'Pop Culture English', pt: 'Inglês pela Cultura Pop',
    desc: { en: 'Learn English through movies, music, memes and social media', pt: 'Aprenda inglês por filmes, música, memes e redes sociais' },
    weeks: [
      { week:1, theme:{en:'Movies & TV Shows',pt:'Filmes & Séries'}, tasks:[
        {id:'pc1',en:'Watch a 10-min clip and note 10 new words',pt:'Assistir trecho e anotar 10 palavras novas',cat:'listening'},
        {id:'pc2',en:'Movie genres: thriller, comedy, sci-fi, romance',pt:'Gêneros de filmes em inglês',cat:'vocab'},
        {id:'pc3',en:'Discuss a favorite movie: plot, characters, themes',pt:'Discutir um filme favorito',cat:'speaking'},
        {id:'pc4',en:'American vs British expressions in TV shows',pt:'Expressões americanas vs britânicas em séries',cat:'vocab'},
        {id:'pc5',en:'Write a movie review in English (100 words)',pt:'Crítica de filme em inglês',cat:'writing'},
      ]},
      { week:2, theme:{en:'Music & Lyrics',pt:'Música & Letras'}, tasks:[
        {id:'pc6',en:'Analyze song lyrics for vocabulary and grammar',pt:'Analisar letras para vocabulário e gramática',cat:'listening'},
        {id:'pc7',en:'Musical genres: pop, indie, hip-hop, R&B',pt:'Gêneros musicais e vocabulário',cat:'vocab'},
        {id:'pc8',en:'Discuss what makes a song meaningful',pt:'Discutir o que torna uma música significativa',cat:'speaking'},
        {id:'pc9',en:'Idioms and phrases from popular songs',pt:'Expressões de músicas populares',cat:'vocab'},
        {id:'pc10',en:'Recommend an English song and explain why',pt:'Recomendar uma música em inglês',cat:'speaking'},
      ]},
      { week:3, theme:{en:'Social Media',pt:'Redes Sociais'}, tasks:[
        {id:'pc11',en:'Social media vocabulary: scroll, swipe, follow, like, share',pt:'Vocabulário de redes sociais',cat:'vocab'},
        {id:'pc12',en:'Internet slang: FOMO, GOAT, TBH, lowkey, slay, vibe',pt:'Gírias da internet',cat:'vocab'},
        {id:'pc13',en:'Write a social media caption for a photo',pt:'Escreva uma legenda em inglês',cat:'writing'},
        {id:'pc14',en:'Explain a popular meme in English',pt:'Explicar um meme popular em inglês',cat:'speaking'},
        {id:'pc15',en:'Create a mock Instagram post about your day',pt:'Post fictício no Instagram sobre seu dia',cat:'writing'},
      ]},
      { week:4, theme:{en:'Podcasts & YouTube',pt:'Podcasts & YouTube'}, tasks:[
        {id:'pc16',en:'Listen to a 5-min podcast and summarize',pt:'Ouvir podcast e resumir os pontos',cat:'listening'},
        {id:'pc17',en:'Podcast vocabulary: episode, host, guest, subscribe',pt:'Vocabulário de podcasts',cat:'vocab'},
        {id:'pc18',en:'Watch a YouTube video and take notes',pt:'Assistir vídeo e anotar ideias-chave',cat:'listening'},
        {id:'pc19',en:'Write comments in English on YouTube',pt:'Escrever comentários em inglês',cat:'writing'},
        {id:'pc20',en:'Recommend a podcast or channel to Teacher Renata',pt:'Recomendar podcast ou canal',cat:'speaking'},
      ]},
      { week:5, theme:{en:'Books & Literature',pt:'Livros & Literatura'}, tasks:[
        {id:'pc21',en:'Read a 1-page excerpt and discuss',pt:'Ler trecho de livro e discutir',cat:'reading'},
        {id:'pc22',en:'Book genres: thriller, romance, sci-fi, biography',pt:'Gêneros literários',cat:'vocab'},
        {id:'pc23',en:'Discuss a favorite book: plot, characters, themes',pt:'Discutir um livro favorito',cat:'speaking'},
        {id:'pc24',en:'Idioms from classic English literature',pt:'Expressões da literatura clássica',cat:'vocab'},
        {id:'pc25',en:'Write a 100-word book recommendation',pt:'Recomendação de livro em inglês',cat:'writing'},
      ]},
      { week:6, theme:{en:'Sports & Games',pt:'Esportes & Jogos'}, tasks:[
        {id:'pc26',en:'Sports vocabulary: score, match, championship, draw',pt:'Vocabulário de esportes',cat:'vocab'},
        {id:'pc27',en:'Discussing sports: Who do you think will win?',pt:'Discutir eventos esportivos',cat:'speaking'},
        {id:'pc28',en:'Video game vocabulary: level, boss, respawn, loot',pt:'Vocabulário de videogames',cat:'vocab'},
        {id:'pc29',en:'Sports idioms: ballpark, on the ball, kick off',pt:'Expressões esportivas no dia a dia',cat:'vocab'},
        {id:'pc30',en:"Describe your favorite sport to someone who doesn't know it",pt:'Descrever seu esporte favorito',cat:'speaking'},
      ]},
      { week:7, theme:{en:'News & Current Events',pt:'Notícias & Atualidades'}, tasks:[
        {id:'pc31',en:'Read a BBC or CNN article and summarize (50 words)',pt:'Resumir artigo da BBC ou CNN',cat:'reading'},
        {id:'pc32',en:'News vocabulary: headline, breaking news, editorial',pt:'Vocabulário de notícias',cat:'vocab'},
        {id:'pc33',en:'Discuss a current global event with your opinion',pt:'Discutir evento global com sua opinião',cat:'speaking'},
        {id:'pc34',en:'Media literacy: fact vs opinion, bias in reporting',pt:'Fato vs opinião, viés na reportagem',cat:'reading'},
        {id:'pc35',en:'Write a 100-word news report about an event',pt:'Notícia de 100 palavras',cat:'writing'},
      ]},
      { week:8, theme:{en:'Food Culture',pt:'Cultura Gastronômica'}, tasks:[
        {id:'pc36',en:'Food trends: plant-based, farm-to-table, fusion',pt:'Tendências gastronômicas',cat:'vocab'},
        {id:'pc37',en:'Describe a recipe: ingredients and steps',pt:'Descrever uma receita em inglês',cat:'speaking'},
        {id:'pc38',en:'Food idioms: piece of cake, bite off more than you can chew',pt:'Expressões idiomáticas sobre comida',cat:'vocab'},
        {id:'pc39',en:'Watch a cooking show clip in English',pt:'Assistir programa culinário em inglês',cat:'listening'},
        {id:'pc40',en:'Teach Teacher Renata how to make a Brazilian dish',pt:'Ensinar Teacher Renata a fazer prato brasileiro',cat:'speaking'},
      ]},
      { week:9, theme:{en:'Fashion & Art',pt:'Moda & Arte'}, tasks:[
        {id:'pc41',en:'Fashion vocabulary: trend, collection, sustainable, vintage',pt:'Vocabulário de moda',cat:'vocab'},
        {id:'pc42',en:'Describe an outfit or style in detail',pt:'Descrever um look em inglês',cat:'speaking'},
        {id:'pc43',en:'Art vocabulary: abstract, portrait, gallery, medium',pt:'Vocabulário de arte',cat:'vocab'},
        {id:'pc44',en:'Describe and interpret a piece of art',pt:'Descrever e interpretar obra de arte',cat:'speaking'},
        {id:'pc45',en:'Write about art or fashion that inspires you',pt:'Escrever sobre arte ou moda que te inspira',cat:'writing'},
      ]},
      { week:10, theme:{en:'Technology',pt:'Tecnologia'}, tasks:[
        {id:'pc46',en:'Tech vocabulary: AI, algorithm, cloud, startup, disruptive',pt:'Vocabulário de tecnologia',cat:'vocab'},
        {id:'pc47',en:'Discuss the impact of a technology on daily life',pt:'Impacto de uma tecnologia na vida',cat:'speaking'},
        {id:'pc48',en:'Tech idioms: on the same page, bandwidth, deep dive',pt:'Expressões idiomáticas de tecnologia',cat:'vocab'},
        {id:'pc49',en:'Read a tech article and find 10 new words',pt:'Artigo de tech e 10 palavras novas',cat:'reading'},
        {id:'pc50',en:'Present your opinion on a tech trend (2 minutes)',pt:'Opinião sobre tendência tecnológica',cat:'speaking'},
      ]},
      { week:11, theme:{en:'Travel & Culture',pt:'Viagens & Cultura'}, tasks:[
        {id:'pc51',en:'Travel vocabulary: itinerary, layover, jet lag, hostel',pt:'Vocabulário de viagens',cat:'vocab'},
        {id:'pc52',en:'Describe your dream travel destination',pt:'Descrever destino dos sonhos',cat:'speaking'},
        {id:'pc53',en:'Cultural curiosities from English-speaking countries',pt:'Curiosidades de países anglófonos',cat:'vocab'},
        {id:'pc54',en:'Read travel blogs and identify useful phrases',pt:'Ler blogs de viagem e identificar frases',cat:'reading'},
        {id:'pc55',en:'Write a travel blog post about a real or imaginary trip',pt:'Post de blog sobre viagem',cat:'writing'},
      ]},
      { week:12, theme:{en:'English in Your Daily Life',pt:'Inglês no Seu Dia a Dia'}, tasks:[
        {id:'pc56',en:'Find 5 moments in your day where English appears',pt:'Encontrar inglês no seu cotidiano',cat:'speaking'},
        {id:'pc57',en:'Create a personal English learning playlist',pt:'Criar playlist pessoal de aprendizado',cat:'vocab'},
        {id:'pc58',en:'Change your phone language to English for one week',pt:'Mudar idioma do celular para inglês',cat:'vocab'},
        {id:'pc59',en:'Share your favorite English content with Teacher Renata',pt:'Compartilhar conteúdo favorito em inglês',cat:'speaking'},
        {id:'pc60',en:'Final: how has English become part of your culture?',pt:'Final: como o inglês virou parte da sua cultura?',cat:'speaking'},
      ]},
    ]
  },
  {
    id: 'speaking', icon: '🎙️', color: '#5C6F4F',
    en: 'Confident Speaking', pt: 'Fala com Confiança',
    desc: { en: 'Overcome fear and speak with confidence and clarity', pt: 'Supere o medo e fale com confiança' },
    weeks: [
      { week:1, theme:{en:'Overcoming Anxiety',pt:'Superar a Ansiedade'}, tasks:[
        {id:'sp1',en:'Identify your speaking triggers: what makes you freeze?',pt:'Identificar gatilhos de ansiedade',cat:'speaking'},
        {id:'sp2',en:'Breathing techniques to reduce speaking anxiety',pt:'Técnicas de respiração para reduzir ansiedade',cat:'speaking'},
        {id:'sp3',en:"Power phrases to buy time: Let me think… / Good question!",pt:'Frases para ganhar tempo',cat:'speaking'},
        {id:'sp4',en:'Record yourself speaking for 2 minutes without stopping',pt:'Gravar-se por 2 minutos sem parar',cat:'speaking'},
        {id:'sp5',en:'Self-introduction: who you are, what you do, what you love',pt:'Apresentação pessoal completa',cat:'speaking'},
      ]},
      { week:2, theme:{en:'Pronunciation Basics',pt:'Pronúncia: Fundamentos'}, tasks:[
        {id:'sp6',en:'Minimal pairs: ship/sheep, live/leave, hit/heat',pt:'Pares mínimos: sons difíceis para brasileiros',cat:'pronunciation'},
        {id:'sp7',en:'TH sound: think (θ) and this (ð) - tongue position',pt:'Som TH: posição correta da língua',cat:'pronunciation'},
        {id:'sp8',en:'Word stress: PHOtograph vs phoTOGraphy',pt:'Ênfase em palavras',cat:'pronunciation'},
        {id:'sp9',en:'Silent letters: know, write, island, psychology',pt:'Letras silenciosas em inglês',cat:'pronunciation'},
        {id:'sp10',en:'Read a paragraph aloud and record yourself',pt:'Ler parágrafo em voz alta e gravar',cat:'pronunciation'},
      ]},
      { week:3, theme:{en:'Rhythm & Stress',pt:'Ritmo & Ênfase'}, tasks:[
        {id:'sp11',en:'Content words vs function words: which get stressed?',pt:'Palavras de conteúdo vs função',cat:'pronunciation'},
        {id:'sp12',en:'Rhythm: stress-timed English vs syllable-timed Portuguese',pt:'Ritmo em inglês diferente do português',cat:'pronunciation'},
        {id:'sp13',en:'Stress changes meaning: I LOVE him vs I love HIM',pt:'Mudar ênfase muda significado',cat:'pronunciation'},
        {id:'sp14',en:'Shadowing: copy a native speaker exactly',pt:'Shadowing: copiar nativo exatamente',cat:'pronunciation'},
        {id:'sp15',en:'Read a dialogue with correct rhythm and stress',pt:'Ler diálogo com ritmo correto',cat:'pronunciation'},
      ]},
      { week:4, theme:{en:'Connected Speech',pt:'Fala Conectada'}, tasks:[
        {id:'sp16',en:'Linking: final consonant + initial vowel (pick_it_up)',pt:'Ligação: consoante final + vogal inicial',cat:'pronunciation'},
        {id:'sp17',en:'Reduction: gonna, wanna, kinda, hafta, shoulda',pt:'Reduções naturais na fala',cat:'pronunciation'},
        {id:'sp18',en:'Elision: dropping sounds in fast speech',pt:'Sons suprimidos na fala rápida',cat:'pronunciation'},
        {id:'sp19',en:'Listen and identify connected speech features',pt:'Identificar fala conectada em nativo',cat:'listening'},
        {id:'sp20',en:'Practice 5 sentences with natural connected speech',pt:'Praticar 5 frases com velocidade natural',cat:'pronunciation'},
      ]},
      { week:5, theme:{en:'Intonation',pt:'Entonação'}, tasks:[
        {id:'sp21',en:'Rising intonation: yes/no questions and uncertainty',pt:'Entonação ascendente: perguntas',cat:'pronunciation'},
        {id:'sp22',en:'Falling intonation: statements and finished thoughts',pt:'Entonação descendente: afirmações',cat:'pronunciation'},
        {id:'sp23',en:'Emotions through intonation: excited, bored, surprised',pt:'Emoções pela entonação',cat:'pronunciation'},
        {id:'sp24',en:'Sarcasm: how intonation reveals true meaning',pt:'Sarcasmo pela entonação',cat:'pronunciation'},
        {id:'sp25',en:'Say the same sentence 5 ways with different intonations',pt:'Mesma frase com 5 entonações diferentes',cat:'pronunciation'},
      ]},
      { week:6, theme:{en:'Fluency Building',pt:'Construindo Fluência'}, tasks:[
        {id:'sp26',en:'Speak for 1 minute on any topic without stopping',pt:'Falar 1 minuto sobre qualquer tema',cat:'speaking'},
        {id:'sp27',en:'Describe a picture in detail for 2 minutes',pt:'Descrever uma imagem por 2 minutos',cat:'speaking'},
        {id:'sp28',en:'Retell a movie or book story from memory',pt:'Recontar filme ou livro de memória',cat:'speaking'},
        {id:'sp29',en:'Rapid-fire: answer 10 questions quickly',pt:'Responder 10 perguntas rapidamente',cat:'speaking'},
        {id:'sp30',en:'Record and identify where you hesitate most',pt:'Identificar onde hesita mais',cat:'speaking'},
      ]},
      { week:7, theme:{en:'Public Speaking',pt:'Falar em Público'}, tasks:[
        {id:'sp31',en:"Structure a speech: hook, points, memorable close",pt:'Estruturar um discurso curto',cat:'speaking'},
        {id:'sp32',en:'Eye contact, posture and gesture for confidence',pt:'Contato visual, postura e gestos',cat:'speaking'},
        {id:'sp33',en:"Using pauses effectively: don't fear silence",pt:'Usar pausas efetivamente',cat:'speaking'},
        {id:'sp34',en:'Managing nerves before and during presentations',pt:'Gerenciar nervosismo em apresentações',cat:'speaking'},
        {id:'sp35',en:'Deliver a 3-minute speech on a topic you love',pt:'Discurso de 3 minutos sobre tema que você ama',cat:'speaking'},
      ]},
      { week:8, theme:{en:'Spontaneous Speaking',pt:'Fala Espontânea'}, tasks:[
        {id:'sp36',en:'IELTS-style: 2 minutes on a random topic',pt:'Tarefa estilo IELTS: 2 min sobre tema aleatório',cat:'speaking'},
        {id:'sp37',en:'Think on your feet: respond to unexpected questions',pt:'Responder perguntas inesperadas',cat:'speaking'},
        {id:'sp38',en:'Describe a complex idea in simple English',pt:'Descrever ideia complexa em inglês simples',cat:'speaking'},
        {id:'sp39',en:'Disagree confidently without sounding rude',pt:'Discordar com confiança',cat:'speaking'},
        {id:'sp40',en:'10-minute unscripted conversation',pt:'Conversa não roteirizada de 10 minutos',cat:'speaking'},
      ]},
      { week:9, theme:{en:'Accent & Identity',pt:'Sotaque & Identidade'}, tasks:[
        {id:'sp41',en:'Your accent is part of your identity: embrace it',pt:'Seu sotaque é parte da sua identidade',cat:'speaking'},
        {id:'sp42',en:'Intelligibility over perfection: be understood, not perfect',pt:'Inteligibilidade acima da perfeição',cat:'speaking'},
        {id:'sp43',en:'Brazilian English sounds that confuse listeners',pt:'Sons brasileiros que confundem ouvintes',cat:'pronunciation'},
        {id:'sp44',en:'Improve clarity without losing your accent',pt:'Melhorar clareza sem perder sotaque',cat:'pronunciation'},
        {id:'sp45',en:'Discuss: what does "speaking good English" mean?',pt:'Discussão: o que é falar inglês bem?',cat:'speaking'},
      ]},
      { week:10, theme:{en:'Real-World Practice',pt:'Prática no Mundo Real'}, tasks:[
        {id:'sp46',en:'Join an English conversation group or exchange',pt:'Participar de grupo de conversação',cat:'speaking'},
        {id:'sp47',en:'Watch a TED Talk and discuss the ideas',pt:'Assistir TED Talk e discutir ideias',cat:'listening'},
        {id:'sp48',en:'Comment on a YouTube video or post in English',pt:'Comentar em vídeo ou post em inglês',cat:'writing'},
        {id:'sp49',en:'Order food or coffee in English (live or roleplay)',pt:'Pedir comida ou café em inglês',cat:'speaking'},
        {id:'sp50',en:'What real-world speaking moment do you want to conquer?',pt:'Que situação real você quer conquistar?',cat:'speaking'},
      ]},
      { week:11, theme:{en:'Advanced Conversation',pt:'Conversação Avançada'}, tasks:[
        {id:'sp51',en:'Turn-taking: enter and exit conversations naturally',pt:'Turnos de fala naturalmente',cat:'speaking'},
        {id:'sp52',en:'Topic-shifting: change subjects smoothly',pt:'Mudar de assunto suavemente',cat:'speaking'},
        {id:'sp53',en:'Keep conversation going: questions, reactions',pt:'Manter a conversa fluindo',cat:'speaking'},
        {id:'sp54',en:'Handle misunderstandings: clarify, rephrase, confirm',pt:'Lidar com mal-entendidos',cat:'speaking'},
        {id:'sp55',en:'15-minute free conversation with Teacher Renata',pt:'Conversa livre de 15 minutos',cat:'speaking'},
      ]},
      { week:12, theme:{en:'Your Breakthrough',pt:'Seu Grande Avanço'}, tasks:[
        {id:'sp56',en:'Record the same text as Week 1 — hear your progress',pt:'Gravar o mesmo texto da Semana 1 e ouvir o progresso',cat:'speaking'},
        {id:'sp57',en:'What 3 things improved most in your speaking?',pt:'3 coisas que mais melhoraram na sua fala',cat:'speaking'},
        {id:'sp58',en:'Tell Teacher Renata your story in English',pt:'Contar sua jornada para Teacher Renata',cat:'speaking'},
        {id:'sp59',en:'Set your next 3 speaking goals',pt:'Definir próximos 3 objetivos de fala',cat:'speaking'},
        {id:'sp60',en:'Final: impromptu speech on "Why I learn English"',pt:'Final: discurso improvisado "Por que aprendo inglês"',cat:'speaking'},
      ]},
    ]
  },
  {
    id: 'exam', icon: '🎓', color: '#2D5016',
    en: 'Exam Prep', pt: 'Preparação para Exames',
    desc: { en: 'Prepare for IELTS, TOEFL, Cambridge and other exams', pt: 'Prepare-se para IELTS, TOEFL, Cambridge e outros' },
    weeks: [
      { week:1, theme:{en:'Know Your Exam',pt:'Conhecer o Exame'}, tasks:[
        {id:'ex1',en:'IELTS vs TOEFL vs Cambridge vs TOEIC: which fits you?',pt:'Qual exame é certo para você?',cat:'reading'},
        {id:'ex2',en:'Exam format: sections, timing, question types',pt:'Formato do exame: seções e tempo',cat:'reading'},
        {id:'ex3',en:'Set your target score and what it means for you',pt:'Definir nota alvo',cat:'reading'},
        {id:'ex4',en:'Create a 12-week study schedule',pt:'Cronograma de 12 semanas',cat:'writing'},
        {id:'ex5',en:'Take a diagnostic test to identify weak areas',pt:'Teste diagnóstico para identificar pontos fracos',cat:'reading'},
      ]},
      { week:2, theme:{en:'Reading Skills',pt:'Habilidades de Leitura'}, tasks:[
        {id:'ex6',en:'Skimming: general idea in 2 minutes',pt:'Skimming: ideia geral em 2 minutos',cat:'reading'},
        {id:'ex7',en:'Scanning: find specific information quickly',pt:'Scanning: informação específica',cat:'reading'},
        {id:'ex8',en:'True/False/Not Given: key strategies',pt:'Verdadeiro/Falso/Não Dado: estratégias',cat:'reading'},
        {id:'ex9',en:'Matching headings to paragraphs',pt:'Relacionar títulos a parágrafos',cat:'reading'},
        {id:'ex10',en:'Practice: read an academic text and answer questions',pt:'Texto acadêmico e questões',cat:'reading'},
      ]},
      { week:3, theme:{en:'Listening Skills',pt:'Habilidades de Audição'}, tasks:[
        {id:'ex11',en:'Predict before you listen: context and questions',pt:'Prever antes de ouvir',cat:'listening'},
        {id:'ex12',en:'Note-taking: abbreviations and symbols',pt:'Tomar notas: abreviações',cat:'listening'},
        {id:'ex13',en:'Multiple choice: eliminate wrong answers first',pt:'Múltipla escolha: eliminar erradas',cat:'listening'},
        {id:'ex14',en:'Map/diagram labeling tasks',pt:'Questões de mapa e diagrama',cat:'listening'},
        {id:'ex15',en:'Practice: exam-level recording and questions',pt:'Gravação nível exame',cat:'listening'},
      ]},
      { week:4, theme:{en:'Writing Task 1',pt:'Escrita Tarefa 1'}, tasks:[
        {id:'ex16',en:'Describe charts: overview, key features, data',pt:'Descrever gráficos com visão geral',cat:'writing'},
        {id:'ex17',en:'Process diagrams: first, then, finally, subsequently',pt:'Diagramas de processo',cat:'writing'},
        {id:'ex18',en:'Map tasks: describe changes over time',pt:'Tarefas de mapa: mudanças ao longo do tempo',cat:'writing'},
        {id:'ex19',en:'150-word minimum, no personal opinion in Task 1',pt:'Mínimo 150 palavras, sem opinião na Tarefa 1',cat:'writing'},
        {id:'ex20',en:'Write Task 1 from a real exam chart',pt:'Tarefa 1 com gráfico real de exame',cat:'writing'},
      ]},
      { week:5, theme:{en:'Writing Task 2',pt:'Escrita Tarefa 2'}, tasks:[
        {id:'ex21',en:'Task 2 types: opinion, discussion, problem/solution',pt:'Tipos: opinião, discussão, problema/solução',cat:'writing'},
        {id:'ex22',en:'Introduction: paraphrase the question, state your thesis',pt:'Introdução: parafrasear e tese',cat:'writing'},
        {id:'ex23',en:'Body paragraphs: PEEL (Point, Evidence, Explain, Link)',pt:'Parágrafos: estrutura PEEL',cat:'writing'},
        {id:'ex24',en:'Conclusion: restate thesis, summarize, final thought',pt:'Conclusão eficaz',cat:'writing'},
        {id:'ex25',en:'Write a full 250-word Task 2 essay in 40 minutes',pt:'Redação de 250 palavras em 40 minutos',cat:'writing'},
      ]},
      { week:6, theme:{en:'Speaking Part 1',pt:'Fala Parte 1'}, tasks:[
        {id:'ex26',en:'Part 1 topics: home, work, hobbies, travel, family',pt:'Temas da Parte 1',cat:'speaking'},
        {id:'ex27',en:'Extend answers: give reasons and examples',pt:'Desenvolver respostas com razões',cat:'speaking'},
        {id:'ex28',en:'Natural responses: avoid memorized scripts',pt:'Respostas naturais',cat:'speaking'},
        {id:'ex29',en:'Vocabulary: express preferences and habits',pt:'Vocabulário: preferências e hábitos',cat:'speaking'},
        {id:'ex30',en:'Practice 10 Part 1 questions with 30-second responses',pt:'10 questões da Parte 1',cat:'speaking'},
      ]},
      { week:7, theme:{en:'Speaking Part 2',pt:'Fala Parte 2'}, tasks:[
        {id:'ex31',en:'Cue card: use the bullet points as a guide',pt:'Cue card: usar os tópicos como guia',cat:'speaking'},
        {id:'ex32',en:'1-minute preparation: note key ideas quickly',pt:'Preparação de 1 minuto',cat:'speaking'},
        {id:'ex33',en:'Speak 2 full minutes: pacing and fluency',pt:'Falar 2 minutos completos',cat:'speaking'},
        {id:'ex34',en:'Mix tenses naturally: past, present and future',pt:'Misturar tempos verbais naturalmente',cat:'grammar'},
        {id:'ex35',en:'Practice 3 cue cards with 2-minute responses',pt:'3 cue cards com respostas de 2 minutos',cat:'speaking'},
      ]},
      { week:8, theme:{en:'Speaking Part 3',pt:'Fala Parte 3'}, tasks:[
        {id:'ex36',en:'Abstract topics: society, technology, environment',pt:'Temas abstratos',cat:'speaking'},
        {id:'ex37',en:'Speculating: It might be… / One reason could be…',pt:'Especular em inglês',cat:'speaking'},
        {id:'ex38',en:'Two sides: On one hand… / However…',pt:'Dois lados do argumento',cat:'speaking'},
        {id:'ex39',en:"Develop ideas at length: not one-line answers",pt:'Desenvolver ideias longamente',cat:'speaking'},
        {id:'ex40',en:'Mock Part 3: 5 abstract questions in depth',pt:'Simulado Parte 3: 5 questões abstratas',cat:'speaking'},
      ]},
      { week:9, theme:{en:'Exam Vocabulary',pt:'Vocabulário para Exames'}, tasks:[
        {id:'ex41',en:'Academic Word List: top 50 for all sections',pt:'50 palavras acadêmicas essenciais',cat:'vocab'},
        {id:'ex42',en:'Topic vocabulary: environment, health, education, tech',pt:'Vocabulário por tema',cat:'vocab'},
        {id:'ex43',en:'Synonyms: big=substantial, good=beneficial',pt:'Sinônimos para palavras comuns',cat:'vocab'},
        {id:'ex44',en:'Collocations: make a decision, raise awareness',pt:'Colocações essenciais',cat:'vocab'},
        {id:'ex45',en:'Create flashcards for 30 exam-level words',pt:'Flashcards de 30 palavras nível exame',cat:'vocab'},
      ]},
      { week:10, theme:{en:'Exam Grammar',pt:'Gramática para Exames'}, tasks:[
        {id:'ex46',en:'Grammatical range: variety of structures',pt:'Variedade gramatical',cat:'grammar'},
        {id:'ex47',en:'Complex sentences: relative clauses, conditionals, passives',pt:'Frases complexas',cat:'grammar'},
        {id:'ex48',en:'Common errors that cost points',pt:'Erros comuns que custam pontos',cat:'grammar'},
        {id:'ex49',en:'Proofread your own writing for grammar',pt:'Revisar sua própria escrita',cat:'grammar'},
        {id:'ex50',en:'Write a paragraph using 5+ different grammar structures',pt:'Parágrafo com 5+ estruturas',cat:'grammar'},
      ]},
      { week:11, theme:{en:'Mock Exam',pt:'Simulado Completo'}, tasks:[
        {id:'ex51',en:'Full reading section under time pressure',pt:'Seção de leitura sob pressão',cat:'reading'},
        {id:'ex52',en:'Full listening section with audio',pt:'Seção de audição completa',cat:'listening'},
        {id:'ex53',en:'Task 1 + Task 2 in 60 minutes total',pt:'Tarefa 1 + 2 em 60 minutos',cat:'writing'},
        {id:'ex54',en:'All 3 speaking parts simulated',pt:'Todas as 3 partes de fala',cat:'speaking'},
        {id:'ex55',en:'Review mock: top 3 areas to improve',pt:'Revisar simulado: 3 áreas a melhorar',cat:'reading'},
      ]},
      { week:12, theme:{en:'Exam Day Strategies',pt:'Estratégias no Dia'}, tasks:[
        {id:'ex56',en:'Time management in each section',pt:'Gestão do tempo em cada seção',cat:'speaking'},
        {id:'ex57',en:'Unknown answers: educated guessing',pt:'Estratégia de chute educado',cat:'speaking'},
        {id:'ex58',en:'Day before: rest, light review, confidence',pt:'Véspera: descanso e revisão leve',cat:'speaking'},
        {id:'ex59',en:'Exam-day anxiety: breathing and focus',pt:'Ansiedade: respiração e foco',cat:'speaking'},
        {id:'ex60',en:"Final: review all you've achieved in 12 weeks",pt:'Final: tudo que você conquistou',cat:'speaking'},
      ]},
    ]
  },
]

export const JOURNEY_MAP = Object.fromEntries(JOURNEYS.map(j => [j.id, j]))
