// Leveled activities for the "Conversation Focus" (cv) journey.
// Same rules as the Core English journey: activity type matches the topic's
// purpose, and every activity has beginner / intermediate / advanced variants.
// Non-interactive topics (speaking / listening / pronunciation) are cleared so
// the old mismatched exercises no longer appear; they rely on external links.

const a = (id, type, beginner, intermediate, advanced) => ({ id, type, levels: { beginner, intermediate, advanced } })

const NO_ACTS = ["cv1","cv2","cv3","cv4","cv5","cv6","cv7","cv8","cv9","cv10","cv12","cv13","cv15","cv16","cv17","cv18","cv19","cv20","cv22","cv24","cv25","cv26","cv27","cv28","cv29","cv30","cv32","cv33","cv34","cv35","cv36","cv37","cv38","cv39","cv40","cv42","cv43","cv44","cv45","cv48","cv49","cv50","cv51","cv52","cv53","cv54","cv55","cv56","cv57","cv58","cv59","cv60"]

export const JOURNEY_CV = {}
for (const id of NO_ACTS) JOURNEY_CV[id] = { acts: [] }

Object.assign(JOURNEY_CV, {
  // ─── GRAMMAR ───────────────────────────────────────────────
  cv11: {
    context: "Tempos narrativos: usamos o Past Simple para a ação principal, o Past Continuous para o pano de fundo em progresso, e o Past Perfect para o que aconteceu antes.",
    acts: [
      a('cv11_a1', 'gapdrop',
        { prompt: "I ___ TV when the phone rang.", options: ["watch", "watched", "was watching", "had watched"], answerIdx: 2, hint: "Ação em progresso interrompida → Past Continuous." },
        { prompt: "When I arrived, the film ___ already ___.", options: ["was / starting", "had / started", "has / started", "did / start"], answerIdx: 1, hint: "Antes de outra ação passada → Past Perfect." },
        { prompt: "She ___ for hours before she finally ___ asleep.", options: ["was reading / fell", "had been reading / fell", "read / had fallen", "read / was falling"], answerIdx: 1, hint: "Duração antes de outra ação → Past Perfect Continuous." }),
      a('cv11_a2', 'gapdrop',
        { prompt: "While we ___ dinner, the lights went out.", options: ["had", "were having", "have", "had had"], answerIdx: 1, hint: "'While' + ação em progresso → Past Continuous." },
        { prompt: "By the time help arrived, the storm ___.", options: ["passed", "was passing", "had passed", "passes"], answerIdx: 2, hint: "'By the time' + passado → Past Perfect." },
        { prompt: "No sooner ___ the door than the alarm went off.", options: ["I opened", "had I opened", "I had opened", "did I open"], answerIdx: 1, hint: "'No sooner' inverte com Past Perfect: had + sujeito + particípio." }),
      a('cv11_a3', 'gapdrop',
        { prompt: "He ___ his keys, so he couldn't get in.", options: ["lost", "was losing", "had lost", "loses"], answerIdx: 2, hint: "Causa anterior → Past Perfect." },
        { prompt: "They ___ along the beach when it started to rain.", options: ["walked", "were walking", "had walked", "walk"], answerIdx: 1, hint: "Pano de fundo → Past Continuous." },
        { prompt: "She was exhausted; she ___ all night.", options: ["worked", "was working", "had been working", "works"], answerIdx: 2, hint: "Explica um estado passado com duração → Past Perfect Continuous." }),
      a('cv11_a4', 'gapdrop',
        { prompt: "The sun ___ when we left the house.", options: ["shone", "was shining", "had shone", "shines"], answerIdx: 1, hint: "Cenário em progresso → Past Continuous." },
        { prompt: "I recognised her at once — we ___ before.", options: ["met", "were meeting", "had met", "meet"], answerIdx: 2, hint: "Antes daquele momento → Past Perfect." },
        { prompt: "Hardly ___ when the guests began to arrive.", options: ["we had finished", "had we finished", "we finished", "did we finish"], answerIdx: 1, hint: "'Hardly' inverte com Past Perfect." }),
      a('cv11_a5', 'fill',
        { prompt: "We ___ (drive) home when we saw the accident.", answer: "were driving", keywords: ["were driving"], hint: "Ação em progresso → was/were + -ing." },
        { prompt: "When I got to the station, the train ___ (leave).", answer: "had left", keywords: ["had left"], hint: "Antes de eu chegar → Past Perfect." },
        { prompt: "She ___ (wait) for over an hour before the bus finally came.", answer: "had been waiting", keywords: ["had been waiting"], hint: "Duração até um ponto passado → Past Perfect Continuous." }),
      a('cv11_a6', 'fill',
        { prompt: "It ___ (rain) when we woke up.", answer: "was raining", keywords: ["was raining"], hint: "Cenário em progresso → Past Continuous." },
        { prompt: "He told me he ___ (already / see) that film.", answer: "had already seen", keywords: ["had already seen"], hint: "Discurso indireto de Present Perfect → Past Perfect." },
        { prompt: "By 2020 they ___ (live) abroad for a decade.", answer: "had been living", keywords: ["had been living", "had lived"], hint: "Duração antes de um ponto passado." }),
      a('cv11_a7', 'order',
        { prompt: "Monte a frase.", tokens: ["I", "was", "cooking", "when", "she", "called"], hint: "Past Continuous + Past Simple." },
        { prompt: "Monte a frase.", tokens: ["The", "match", "had", "finished", "before", "we", "arrived"], hint: "Past Perfect + Past Simple." },
        { prompt: "Monte a frase com inversão.", tokens: ["Never", "before", "had", "I", "felt", "so", "nervous"], hint: "'Never before' + had + sujeito + particípio." }),
      a('cv11_a8', 'order',
        { prompt: "Monte a frase.", tokens: ["They", "were", "talking", "quietly", "in", "the", "corner"], hint: "Past Continuous." },
        { prompt: "Monte a frase.", tokens: ["She", "had", "never", "seen", "the", "sea", "before"], hint: "Past Perfect + before." },
        { prompt: "Monte a frase.", tokens: ["We", "had", "been", "walking", "for", "hours", "when", "it", "got", "dark"], hint: "Past Perfect Continuous + Past Simple." }),
      a('cv11_a9', 'mc',
        { prompt: "Which sentence is correct?", options: ["While I cooked, the phone rang.", "While I was cooking, the phone rang.", "While I had cooked, the phone rang.", "While I cook, the phone rang."], answerIdx: 1, hint: "'While' pede Past Continuous." },
        { prompt: "Choose the correct sentence:", options: ["After she had left, I called her.", "After she left, I had called her.", "After she was leaving, I called.", "After she leaves, I called."], answerIdx: 0, hint: "A ação anterior leva Past Perfect." },
        { prompt: "Choose the most natural narrative sentence:", options: ["I was tired because I ran all day.", "I was tired because I had been running all day.", "I had been tired because I was running.", "I was tired because I was running all day."], answerIdx: 1, hint: "Causa com duração → Past Perfect Continuous." }),
      a('cv11_a10', 'mc',
        { prompt: "Which tense shows the background action?", options: ["Past Simple", "Past Continuous", "Past Perfect", "Present Perfect"], answerIdx: 1, hint: "Pano de fundo em progresso → Past Continuous." },
        { prompt: "Which sentence orders the events correctly?", options: ["When I arrived, they ate.", "When I arrived, they had already eaten.", "When I had arrived, they eat.", "When I arrive, they had eaten."], answerIdx: 1, hint: "Comeram ANTES de eu chegar → Past Perfect." },
        { prompt: "Choose the sentence with correct tense sequence:", options: ["No sooner had I sat down than the show began.", "No sooner I sat down than the show began.", "No sooner did I had sat than the show began.", "No sooner I had sat than the show began."], answerIdx: 0, hint: "No sooner + had + sujeito + particípio + than." }),
    ],
  },

  // ─── VOCAB ─────────────────────────────────────────────────
  cv14: {
    context: "Para narrar com emoção, use adjetivos precisos: thrilled (super animado), devastated (arrasado), anxious (ansioso), relieved (aliviado).",
    acts: [
      a('cv14_a1', 'sort',
        { prompt: "Categorize a emoção como positiva ou negativa.", groups: ["Positive", "Negative"], items: [{ t: "happy", g: "Positive" }, { t: "sad", g: "Negative" }, { t: "excited", g: "Positive" }, { t: "angry", g: "Negative" }], hint: "Sentimento bom x ruim." },
        { prompt: "Categorize a emoção.", groups: ["Positive", "Negative"], items: [{ t: "thrilled", g: "Positive" }, { t: "devastated", g: "Negative" }, { t: "delighted", g: "Positive" }, { t: "furious", g: "Negative" }, { t: "relieved", g: "Positive" }], hint: "'thrilled' = super animado; 'devastated' = arrasado." },
        { prompt: "Categorize a emoção pela intensidade.", groups: ["Mild", "Intense"], items: [{ t: "pleased", g: "Mild" }, { t: "ecstatic", g: "Intense" }, { t: "annoyed", g: "Mild" }, { t: "livid", g: "Intense" }, { t: "content", g: "Mild" }, { t: "heartbroken", g: "Intense" }], hint: "'livid' = furioso; 'ecstatic' = eufórico." }),
      a('cv14_a2', 'sort',
        { prompt: "Categorize a emoção pela situação.", groups: ["Good news", "Bad news"], items: [{ t: "delighted", g: "Good news" }, { t: "disappointed", g: "Bad news" }, { t: "overjoyed", g: "Good news" }, { t: "upset", g: "Bad news" }], hint: "Reação a boa x má notícia." },
        { prompt: "Categorize o sentimento.", groups: ["Fear", "Anger", "Joy"], items: [{ t: "terrified", g: "Fear" }, { t: "furious", g: "Anger" }, { t: "delighted", g: "Joy" }, { t: "anxious", g: "Fear" }, { t: "irritated", g: "Anger" }], hint: "Medo, raiva, alegria." },
        { prompt: "Categorize a emoção pela família.", groups: ["Fear/Worry", "Sadness", "Surprise"], items: [{ t: "apprehensive", g: "Fear/Worry" }, { t: "grief-stricken", g: "Sadness" }, { t: "astonished", g: "Surprise" }, { t: "uneasy", g: "Fear/Worry" }, { t: "sorrowful", g: "Sadness" }, { t: "dumbfounded", g: "Surprise" }], hint: "'apprehensive' = apreensivo; 'dumbfounded' = pasmo." }),
      a('cv14_a3', 'gapdrop',
        { prompt: "She was ___ when she passed the exam.", options: ["sad", "thrilled", "bored", "tired"], answerIdx: 1, hint: "Passou → super feliz (thrilled)." },
        { prompt: "He felt ___ after the long flight was finally over.", options: ["furious", "relieved", "anxious", "devastated"], answerIdx: 1, hint: "Voo acabou → aliviado (relieved)." },
        { prompt: "The unexpected criticism left her feeling utterly ___.", options: ["elated", "deflated", "content", "amused"], answerIdx: 1, hint: "Crítica inesperada → 'deflated' (desanimado)." }),
      a('cv14_a4', 'gapdrop',
        { prompt: "I was ___ to hear the bad news.", options: ["delighted", "upset", "excited", "pleased"], answerIdx: 1, hint: "Má notícia → chateado (upset)." },
        { prompt: "They were ___ when the trip got cancelled.", options: ["thrilled", "disappointed", "relieved", "amused"], answerIdx: 1, hint: "Cancelou → decepcionados." },
        { prompt: "Waiting for the results, she felt increasingly ___.", options: ["serene", "apprehensive", "elated", "indifferent"], answerIdx: 1, hint: "Esperando resultado → apreensiva." }),
      a('cv14_a5', 'gapdrop',
        { prompt: "The children were ___ about the trip.", options: ["excited", "bored", "sad", "angry"], answerIdx: 0, hint: "Viagem → animados." },
        { prompt: "He was ___ that he forgot her birthday.", options: ["proud", "mortified", "delighted", "calm"], answerIdx: 1, hint: "Esqueceu o aniversário → mortificado (envergonhado)." },
        { prompt: "Looking at old photos, she felt a wave of ___.", options: ["nostalgia", "fury", "boredom", "panic"], answerIdx: 0, hint: "Fotos antigas → nostalgia." }),
      a('cv14_a6', 'match',
        { prompt: "Relacione a emoção com sua tradução.", pairs: [{ left: "happy", right: "feliz" }, { left: "angry", right: "com raiva" }, { left: "scared", right: "assustado" }], hint: "Emoções básicas." },
        { prompt: "Relacione a emoção forte com sua tradução.", pairs: [{ left: "thrilled", right: "muito animado" }, { left: "devastated", right: "arrasado" }, { left: "furious", right: "furioso" }, { left: "relieved", right: "aliviado" }], hint: "Versões intensas." },
        { prompt: "Relacione a emoção sutil com sua definição.", pairs: [{ left: "wistful", right: "saudoso e melancólico" }, { left: "indignant", right: "indignado" }, { left: "smug", right: "convencido" }, { left: "apprehensive", right: "apreensivo" }], hint: "Emoções mais nuançadas." }),
      a('cv14_a7', 'match',
        { prompt: "Relacione a emoção com o oposto.", pairs: [{ left: "happy", right: "sad" }, { left: "calm", right: "nervous" }, { left: "brave", right: "scared" }], hint: "Opostos." },
        { prompt: "Relacione a emoção com a situação.", pairs: [{ left: "nervous", right: "before an exam" }, { left: "relieved", right: "after good news" }, { left: "bored", right: "a long wait" }, { left: "proud", right: "an achievement" }], hint: "Quando você sente cada uma." },
        { prompt: "Relacione a emoção intensa com sua versão branda.", pairs: [{ left: "ecstatic", right: "pleased" }, { left: "furious", right: "annoyed" }, { left: "terrified", right: "worried" }, { left: "heartbroken", right: "upset" }], hint: "Intenso → brando." }),
      a('cv14_a8', 'sort',
        { prompt: "Categorize: a emoção descreve o corpo ou a mente?", groups: ["Physical feeling", "Emotion"], items: [{ t: "exhausted", g: "Physical feeling" }, { t: "jealous", g: "Emotion" }, { t: "hungry", g: "Physical feeling" }, { t: "proud", g: "Emotion" }], hint: "Corpo x sentimento." },
        { prompt: "Categorize a reação pela emoção.", groups: ["Joy", "Fear", "Sadness"], items: [{ t: "grinned", g: "Joy" }, { t: "trembled", g: "Fear" }, { t: "wept", g: "Sadness" }, { t: "beamed", g: "Joy" }, { t: "froze", g: "Fear" }], hint: "Ações que revelam a emoção." },
        { prompt: "Categorize a expressão idiomática pela emoção.", groups: ["Very happy", "Very angry", "Very scared"], items: [{ t: "over the moon", g: "Very happy" }, { t: "seeing red", g: "Very angry" }, { t: "scared stiff", g: "Very scared" }, { t: "on cloud nine", g: "Very happy" }, { t: "hit the roof", g: "Very angry" }, { t: "jumped out of one's skin", g: "Very scared" }], hint: "'over the moon' = radiante; 'hit the roof' = explodiu de raiva." }),
      a('cv14_a9', 'mc',
        { prompt: "Which word describes great happiness?", options: ["miserable", "overjoyed", "anxious", "furious"], answerIdx: 1, hint: "'overjoyed' = radiante." },
        { prompt: "'She was on cloud nine' means she was:", options: ["very tired", "extremely happy", "very angry", "confused"], answerIdx: 1, hint: "Idioma de felicidade." },
        { prompt: "Which word best describes quiet, reflective sadness?", options: ["livid", "wistful", "ecstatic", "smug"], answerIdx: 1, hint: "'wistful' = melancólico e saudoso." }),
      a('cv14_a10', 'mc',
        { prompt: "Which is a negative emotion?", options: ["delighted", "devastated", "thrilled", "content"], answerIdx: 1, hint: "'devastated' = arrasado." },
        { prompt: "If you 'hit the roof', you are:", options: ["very happy", "very calm", "very angry", "very sleepy"], answerIdx: 2, hint: "Explodir de raiva." },
        { prompt: "'Indignant' most nearly means:", options: ["angry at something unfair", "pleasantly surprised", "mildly bored", "deeply relaxed"], answerIdx: 0, hint: "Indignado = raiva por injustiça." }),
    ],
  },
  cv21: {
    context: "Humor britânico x americano e diferenças de vocabulário. O britânico ama ironia, sarcasmo e 'understatement' (dizer menos do que se quer); há também palavras diferentes (lift/elevator).",
    acts: [
      a('cv21_a1', 'sort',
        { prompt: "Categorize a palavra: britânica ou americana?", groups: ["British", "American"], items: [{ t: "lift", g: "British" }, { t: "elevator", g: "American" }, { t: "flat", g: "British" }, { t: "apartment", g: "American" }], hint: "lift/flat = UK; elevator/apartment = US." },
        { prompt: "Categorize: britânica ou americana?", groups: ["British", "American"], items: [{ t: "lorry", g: "British" }, { t: "truck", g: "American" }, { t: "biscuit", g: "British" }, { t: "cookie", g: "American" }, { t: "trousers", g: "British" }], hint: "lorry/biscuit/trousers = UK." },
        { prompt: "Categorize: britânica ou americana?", groups: ["British", "American"], items: [{ t: "aubergine", g: "British" }, { t: "eggplant", g: "American" }, { t: "pavement", g: "British" }, { t: "sidewalk", g: "American" }, { t: "queue", g: "British" }, { t: "line", g: "American" }], hint: "aubergine/pavement/queue = UK." }),
      a('cv21_a2', 'sort',
        { prompt: "Categorize o tipo de humor.", groups: ["Sarcasm", "Silliness"], items: [{ t: "\"Oh, great. Another meeting.\"", g: "Sarcasm" }, { t: "A pie in the face", g: "Silliness" }, { t: "\"Nice weather... for ducks.\"", g: "Sarcasm" }, { t: "Silly walks", g: "Silliness" }], hint: "Sarcasmo diz o oposto; besteira é físico/bobo." },
        { prompt: "Categorize o recurso de humor.", groups: ["Irony", "Exaggeration"], items: [{ t: "Calling a huge dog 'Tiny'", g: "Irony" }, { t: "\"I've told you a million times\"", g: "Exaggeration" }, { t: "\"Lovely, my flight's delayed again\"", g: "Irony" }, { t: "\"I'm so hungry I could eat a horse\"", g: "Exaggeration" }], hint: "Ironia x hipérbole." },
        { prompt: "Categorize o estilo cômico.", groups: ["Understatement", "Deadpan"], items: [{ t: "Calling a disaster 'a bit of a problem'", g: "Understatement" }, { t: "Joking with a totally straight face", g: "Deadpan" }, { t: "\"It's just a scratch\" about a huge dent", g: "Understatement" }, { t: "No emotion while saying something absurd", g: "Deadpan" }], hint: "'Understatement' minimiza; 'deadpan' é sem expressão." }),
      a('cv21_a3', 'gapdrop',
        { prompt: "In Britain, you wait in a ___.", options: ["line", "queue", "row", "file"], answerIdx: 1, hint: "UK → queue." },
        { prompt: "\"The soup is cold.\" — \"Well, isn't that ___?\" (sarcastic)", options: ["lovely", "terrible", "sad", "fine"], answerIdx: 0, hint: "Sarcasmo diz o oposto → 'lovely'." },
        { prompt: "Describing a hurricane as 'a spot of bad weather' is an example of ___.", options: ["exaggeration", "understatement", "slapstick", "flattery"], answerIdx: 1, hint: "Minimizar algo grande → understatement." }),
      a('cv21_a4', 'gapdrop',
        { prompt: "Americans call it a 'cookie'; the British say ___.", options: ["cake", "biscuit", "cracker", "bun"], answerIdx: 1, hint: "UK → biscuit." },
        { prompt: "Saying \"Oh, brilliant\" when something goes wrong is ___.", options: ["sincere", "sarcastic", "polite", "formal"], answerIdx: 1, hint: "Elogio quando dá errado → sarcasmo." },
        { prompt: "British comedy often relies on ___ — a dry, unemotional delivery.", options: ["slapstick", "deadpan", "flattery", "mime"], answerIdx: 1, hint: "Entrega seca e sem emoção → deadpan." }),
      a('cv21_a5', 'gapdrop',
        { prompt: "In the US you fill the car with 'gas'; in the UK it's ___.", options: ["oil", "petrol", "diesel only", "fuel-water"], answerIdx: 1, hint: "UK → petrol." },
        { prompt: "\"I'm fine,\" he said flatly, having just broken his leg. This is ___.", options: ["understatement", "exaggeration", "flattery", "sincerity"], answerIdx: 0, hint: "Perna quebrada e diz 'fine' → understatement." },
        { prompt: "A joke that mocks its own teller is a form of ___ humour.", options: ["self-deprecating", "slapstick", "observational", "cruel"], answerIdx: 0, hint: "Rir de si mesmo → self-deprecating." }),
      a('cv21_a6', 'match',
        { prompt: "Relacione a palavra britânica com a americana.", pairs: [{ left: "lift", right: "elevator" }, { left: "flat", right: "apartment" }, { left: "lorry", right: "truck" }], hint: "UK → US." },
        { prompt: "Relacione a palavra britânica com a americana.", pairs: [{ left: "petrol", right: "gas" }, { left: "biscuit", right: "cookie" }, { left: "holiday", right: "vacation" }, { left: "rubbish", right: "trash" }], hint: "UK → US." },
        { prompt: "Relacione a palavra britânica com a americana.", pairs: [{ left: "aubergine", right: "eggplant" }, { left: "courgette", right: "zucchini" }, { left: "pavement", right: "sidewalk" }, { left: "jumper", right: "sweater" }], hint: "UK → US (comida e roupa)." }),
      a('cv21_a7', 'match',
        { prompt: "Relacione o tipo de humor com o exemplo.", pairs: [{ left: "sarcasm", right: "\"Great, more rain\"" }, { left: "exaggeration", right: "\"I waited forever\"" }, { left: "silliness", right: "a funny walk" }], hint: "Estilo → exemplo." },
        { prompt: "Relacione o termo de humor com a definição.", pairs: [{ left: "irony", right: "saying the opposite" }, { left: "pun", right: "a play on words" }, { left: "wit", right: "clever, quick humour" }, { left: "banter", right: "playful teasing" }], hint: "Definições de humor." },
        { prompt: "Relacione o estilo com sua descrição.", pairs: [{ left: "deadpan", right: "no facial expression" }, { left: "self-deprecating", right: "mocking oneself" }, { left: "observational", right: "about everyday life" }, { left: "satire", right: "mocking those in power" }], hint: "Estilos cômicos." }),
      a('cv21_a8', 'sort',
        { prompt: "Categorize a palavra pela ortografia.", groups: ["British spelling", "American spelling"], items: [{ t: "colour", g: "British spelling" }, { t: "color", g: "American spelling" }, { t: "theatre", g: "British spelling" }, { t: "theater", g: "American spelling" }], hint: "-our/-re = UK; -or/-er = US." },
        { prompt: "Categorize a ortografia.", groups: ["British spelling", "American spelling"], items: [{ t: "organise", g: "British spelling" }, { t: "organize", g: "American spelling" }, { t: "travelled", g: "British spelling" }, { t: "traveled", g: "American spelling" }, { t: "centre", g: "British spelling" }], hint: "-ise/-lled = UK; -ize/-led = US." },
        { prompt: "Categorize a ortografia.", groups: ["British spelling", "American spelling"], items: [{ t: "defence", g: "British spelling" }, { t: "defense", g: "American spelling" }, { t: "programme", g: "British spelling" }, { t: "program", g: "American spelling" }, { t: "catalogue", g: "British spelling" }, { t: "catalog", g: "American spelling" }], hint: "-ce/-mme/-ogue = UK." }),
      a('cv21_a9', 'mc',
        { prompt: "The British word for 'apartment' is:", options: ["house", "flat", "room", "block"], answerIdx: 1, hint: "UK → flat." },
        { prompt: "\"Oh, wonderful,\" she sighed as the bus drove off without her. This is:", options: ["sincere praise", "sarcasm", "a compliment", "understatement"], answerIdx: 1, hint: "Elogio quando dá errado → sarcasmo." },
        { prompt: "Describing a total catastrophe as 'not ideal' is an example of:", options: ["exaggeration", "understatement", "flattery", "slapstick"], answerIdx: 1, hint: "Minimizar → understatement." }),
      a('cv21_a10', 'mc',
        { prompt: "Which is the American spelling?", options: ["colour", "color", "colur", "coleur"], answerIdx: 1, hint: "US → color." },
        { prompt: "'Banter' between friends is:", options: ["a serious argument", "playful teasing", "silent treatment", "formal debate"], answerIdx: 1, hint: "Brincadeira entre amigos." },
        { prompt: "A pun is humour based on:", options: ["physical falls", "words with double meanings", "mocking politicians", "exaggeration"], answerIdx: 1, hint: "Jogo de palavras / duplo sentido." }),
    ],
  },
  cv23: {
    context: "Trocadilhos (puns) e jogos de palavras exploram palavras com sons iguais (homófonos) ou vários sentidos. Ex.: 'Time flies like an arrow.'",
    acts: [
      a('cv23_a1', 'match',
        { prompt: "Relacione os homófonos (mesmo som).", pairs: [{ left: "flower", right: "flour" }, { left: "sea", right: "see" }, { left: "night", right: "knight" }], hint: "Soam igual, escrevem diferente." },
        { prompt: "Relacione os homófonos.", pairs: [{ left: "pair", right: "pear" }, { left: "write", right: "right" }, { left: "sun", right: "son" }, { left: "hear", right: "here" }], hint: "Mesmo som." },
        { prompt: "Relacione os homófonos.", pairs: [{ left: "principal", right: "principle" }, { left: "stationary", right: "stationery" }, { left: "complement", right: "compliment" }, { left: "bare", right: "bear" }], hint: "Homófonos que confundem até nativos." }),
      a('cv23_a2', 'match',
        { prompt: "Relacione a palavra com um segundo sentido.", pairs: [{ left: "bat", right: "animal or sports stick" }, { left: "bank", right: "money place or riverside" }, { left: "bark", right: "dog sound or tree skin" }], hint: "Palavras com dois sentidos." },
        { prompt: "Relacione a palavra com seus dois sentidos.", pairs: [{ left: "light", right: "not heavy / not dark" }, { left: "match", right: "game / fire stick" }, { left: "spring", right: "season / coil" }, { left: "left", right: "direction / departed" }], hint: "Duplos sentidos." },
        { prompt: "Relacione o verbo com seus sentidos.", pairs: [{ left: "run", right: "jog / manage a business" }, { left: "book", right: "read it / reserve it" }, { left: "charge", right: "price / accuse / power up" }, { left: "draw", right: "sketch / tie in a game" }], hint: "Verbos com múltiplos sentidos." }),
      a('cv23_a3', 'gapdrop',
        { prompt: "\"I used to be a baker, but I couldn't make enough ___.\" (money pun)", options: ["bread", "cake", "flour", "salt"], answerIdx: 0, hint: "'bread' = gíria para dinheiro." },
        { prompt: "Which word sounds the same as 'won'?", options: ["win", "one", "own", "wine"], answerIdx: 1, hint: "'won' e 'one' são homófonos." },
        { prompt: "\"Time flies like an arrow; fruit flies like a ___.\" (pun on 'flies')", options: ["tree", "banana", "bird", "plane"], answerIdx: 1, hint: "Aqui 'flies' vira substantivo (mosca) e 'like' = gosta de." }),
      a('cv23_a4', 'gapdrop',
        { prompt: "A word that sounds like another is a ___.", options: ["synonym", "homophone", "antonym", "prefix"], answerIdx: 1, hint: "Mesmo som → homófono." },
        { prompt: "\"I'm reading a book about anti-gravity. It's impossible to put ___.\"", options: ["up", "down", "away", "off"], answerIdx: 1, hint: "'put down' + anti-gravidade = trocadilho." },
        { prompt: "A pun that relies on two meanings of one word is called a ___.", options: ["homograph pun", "double entendre", "spoonerism", "rhyme"], answerIdx: 1, hint: "Duplo sentido → double entendre." }),
      a('cv23_a5', 'gapdrop',
        { prompt: "\"The ___ said to the flower, 'Nice to meet you, honey!'\" (bee pun)", options: ["cat", "bee", "dog", "fish"], answerIdx: 1, hint: "'honey' + abelha (bee)." },
        { prompt: "Which pair are homophones?", options: ["big / bag", "sea / see", "run / ran", "hot / hat"], answerIdx: 1, hint: "sea/see soam igual." },
        { prompt: "A 'spoonerism' swaps the ___ of two words (e.g. 'well-boiled icicle').", options: ["endings", "initial sounds", "vowels only", "meanings"], answerIdx: 1, hint: "Troca os sons iniciais." }),
      a('cv23_a6', 'sort',
        { prompt: "Categorize: os dois soam igual (homófonos) ou não?", groups: ["Homophones", "Not homophones"], items: [{ t: "to / too", g: "Homophones" }, { t: "cat / cut", g: "Not homophones" }, { t: "buy / by", g: "Homophones" }, { t: "big / bag", g: "Not homophones" }], hint: "Mesmo som exato?" },
        { prompt: "Categorize: homófonos ou não?", groups: ["Homophones", "Not homophones"], items: [{ t: "their / there", g: "Homophones" }, { t: "ship / sheep", g: "Not homophones" }, { t: "week / weak", g: "Homophones" }, { t: "live / leave", g: "Not homophones" }, { t: "flour / flower", g: "Homophones" }], hint: "Cuidado: ship/sheep têm vogais diferentes." },
        { prompt: "Categorize o recurso de humor.", groups: ["Pun (wordplay)", "Not a pun"], items: [{ t: "\"I'm on a seafood diet: I see food and eat it.\"", g: "Pun (wordplay)" }, { t: "A man slips on a banana peel", g: "Not a pun" }, { t: "\"Broken pencils are pointless.\"", g: "Pun (wordplay)" }, { t: "A long, boring story", g: "Not a pun" }], hint: "Pun brinca com as palavras." }),
      a('cv23_a7', 'gapdrop',
        { prompt: "\"Broken pencils are ___.\" (pun: no point / pointless)", options: ["useful", "pointless", "sharp", "heavy"], answerIdx: 1, hint: "'point' do lápis + 'pointless' = sem sentido." },
        { prompt: "Which word can mean both a season and a metal coil?", options: ["summer", "spring", "autumn", "winter"], answerIdx: 1, hint: "'spring' = primavera / mola." },
        { prompt: "\"I wondered why the ball was getting bigger. Then it ___ me.\"", options: ["helped", "hit", "missed", "found"], answerIdx: 1, hint: "'it hit me' = me ocorreu / a bola bateu." }),
      a('cv23_a8', 'match',
        { prompt: "Relacione a palavra com seu homófono.", pairs: [{ left: "eye", right: "I" }, { left: "hour", right: "our" }, { left: "meat", right: "meet" }], hint: "Mesmo som." },
        { prompt: "Relacione a palavra com o outro sentido usado no trocadilho.", pairs: [{ left: "current", right: "electricity / now" }, { left: "date", right: "fruit / meeting" }, { left: "ring", right: "jewellery / phone call" }, { left: "novel", right: "book / new" }], hint: "Duplos sentidos usados em puns." },
        { prompt: "Relacione o trocadilho com o duplo sentido.", pairs: [{ left: "\"a boiled egg is hard to beat\"", right: "beat = whisk / better" }, { left: "\"long fairy tales tend to dragon\"", right: "dragon = drag on" }, { left: "\"I lost my job at the bank\"", right: "lost interest" }, { left: "\"the roundest knight was Sir Cumference\"", right: "circumference" }], hint: "Explica a brincadeira de palavras." }),
      a('cv23_a9', 'mc',
        { prompt: "Which pair are homophones?", options: ["read / red", "big / dog", "hot / hat", "run / ran"], answerIdx: 0, hint: "'read' (passado) e 'red' soam igual." },
        { prompt: "A pun is a joke that plays on:", options: ["falling over", "words and their meanings/sounds", "rude gestures", "long silences"], answerIdx: 1, hint: "Jogo de palavras." },
        { prompt: "\"I'm reading a book on teleportation. It's bound to take me places.\" The pun is on:", options: ["'reading'", "'bound' (certain / tied like a book)", "'book'", "'places'"], answerIdx: 1, hint: "'bound' = com certeza / encadernado." }),
      a('cv23_a10', 'mc',
        { prompt: "Which word has two meanings useful for a pun?", options: ["quickly", "bark", "very", "under"], answerIdx: 1, hint: "'bark' = latido / casca de árvore." },
        { prompt: "'Their', 'there' and 'they're' are:", options: ["synonyms", "homophones", "antonyms", "prefixes"], answerIdx: 1, hint: "Soam igual." },
        { prompt: "\"Whiteboards are remarkable.\" The pun works because 'remarkable' sounds like:", options: ["'re-markable' (can be written on again)", "'remove'", "'remember'", "'markable'"], answerIdx: 0, hint: "re-mark-able = pode ser escrito de novo." }),
    ],
  },
  cv31: {
    context: "Linguagem de festas e eventos: invite, RSVP, host, guest, toast, celebrate. Frases para convidar, aceitar e brindar.",
    acts: [
      a('cv31_a1', 'match',
        { prompt: "Relacione a palavra com sua tradução.", pairs: [{ left: "invite", right: "convidar" }, { left: "guest", right: "convidado" }, { left: "party", right: "festa" }], hint: "Palavras de festa." },
        { prompt: "Relacione a palavra com o significado.", pairs: [{ left: "host", right: "quem dá a festa" }, { left: "RSVP", right: "confirmar presença" }, { left: "toast", right: "brinde" }, { left: "venue", right: "local do evento" }], hint: "Termos de eventos." },
        { prompt: "Relacione a expressão com o sentido.", pairs: [{ left: "throw a party", right: "organise one" }, { left: "the life of the party", right: "the most fun guest" }, { left: "gatecrash", right: "come uninvited" }, { left: "wind down", right: "the party ends slowly" }], hint: "Expressões idiomáticas de festa." }),
      a('cv31_a2', 'match',
        { prompt: "Relacione o tipo de evento.", pairs: [{ left: "wedding", right: "casamento" }, { left: "birthday", right: "aniversário" }, { left: "reunion", right: "reencontro" }], hint: "Tipos de evento." },
        { prompt: "Relacione o evento com sua descrição.", pairs: [{ left: "housewarming", right: "new home party" }, { left: "farewell", right: "goodbye party" }, { left: "reception", right: "formal celebration after" }, { left: "get-together", right: "casual gathering" }], hint: "Eventos e ocasiões." },
        { prompt: "Relacione a frase com a função.", pairs: [{ left: "Cheers!", right: "toasting" }, { left: "Would you like to come?", right: "inviting" }, { left: "I'd love to!", right: "accepting" }, { left: "I'm afraid I can't make it", right: "declining" }], hint: "Convidar, aceitar, recusar, brindar." }),
      a('cv31_a3', 'gapdrop',
        { prompt: "Please ___ by Friday so we know how many are coming.", options: ["RSVP", "toast", "host", "gatecrash"], answerIdx: 0, hint: "Confirmar presença → RSVP." },
        { prompt: "Let's raise a glass and ___ to the happy couple!", options: ["host", "toast", "invite", "cater"], answerIdx: 1, hint: "Brindar → toast." },
        { prompt: "The party really ___ off once the band started playing.", options: ["took", "went", "put", "came"], answerIdx: 0, hint: "'took off' = decolou/animou." }),
      a('cv31_a4', 'gapdrop',
        { prompt: "We're going to ___ a party for her birthday.", options: ["do", "make", "throw", "put"], answerIdx: 2, hint: "'throw a party'." },
        { prompt: "The ___ greeted every guest at the door.", options: ["guest", "host", "waiter", "stranger"], answerIdx: 1, hint: "Quem recebe → host." },
        { prompt: "He turned up without an invitation — he totally ___ the party.", options: ["hosted", "gatecrashed", "catered", "toasted"], answerIdx: 1, hint: "Entrar sem convite → gatecrash." }),
      a('cv31_a5', 'gapdrop',
        { prompt: "Thanks for the ___ — I'd love to come!", options: ["guest", "invitation", "host", "toast"], answerIdx: 1, hint: "O convite → invitation." },
        { prompt: "The wedding ___ was held in a beautiful hotel.", options: ["reception", "invite", "RSVP", "guest"], answerIdx: 0, hint: "Festa após o casamento → reception." },
        { prompt: "By midnight the party had started to ___ down.", options: ["throw", "wind", "take", "gate"], answerIdx: 1, hint: "'wind down' = ir acalmando." }),
      a('cv31_a6', 'sort',
        { prompt: "Categorize: quem convida ou quem é convidado?", groups: ["Host", "Guest"], items: [{ t: "sends invitations", g: "Host" }, { t: "brings a gift", g: "Guest" }, { t: "greets people at the door", g: "Host" }, { t: "says thank you for having me", g: "Guest" }], hint: "Anfitrião x convidado." },
        { prompt: "Categorize a frase pela função.", groups: ["Inviting", "Accepting", "Declining"], items: [{ t: "Do you fancy coming?", g: "Inviting" }, { t: "Count me in!", g: "Accepting" }, { t: "Sorry, I can't make it", g: "Declining" }, { t: "You're welcome to join us", g: "Inviting" }, { t: "Sounds great, I'll be there", g: "Accepting" }], hint: "Convidar, aceitar, recusar." },
        { prompt: "Categorize o vocabulário do evento.", groups: ["People", "Things", "Actions"], items: [{ t: "guest", g: "People" }, { t: "invitation", g: "Things" }, { t: "celebrate", g: "Actions" }, { t: "host", g: "People" }, { t: "venue", g: "Things" }, { t: "RSVP", g: "Actions" }], hint: "Pessoas, coisas, ações." }),
      a('cv31_a7', 'sort',
        { prompt: "Categorize o evento como formal ou informal.", groups: ["Formal", "Informal"], items: [{ t: "gala dinner", g: "Formal" }, { t: "barbecue", g: "Informal" }, { t: "black-tie ball", g: "Formal" }, { t: "house party", g: "Informal" }], hint: "Formal x casual." },
        { prompt: "Categorize a frase de convite pelo registro.", groups: ["Formal", "Informal"], items: [{ t: "We request the pleasure of your company", g: "Formal" }, { t: "Wanna come to mine?", g: "Informal" }, { t: "You are cordially invited", g: "Formal" }, { t: "Pop round on Saturday!", g: "Informal" }], hint: "Registro do convite." },
        { prompt: "Categorize a palavra pelo tipo de celebração.", groups: ["Wedding", "Birthday", "Work event"], items: [{ t: "bride", g: "Wedding" }, { t: "candles", g: "Birthday" }, { t: "conference", g: "Work event" }, { t: "vows", g: "Wedding" }, { t: "cake", g: "Birthday" }, { t: "networking", g: "Work event" }], hint: "Casamento, aniversário, trabalho." }),
      a('cv31_a8', 'gapdrop',
        { prompt: "Everyone sang and we blew out the ___ on the cake.", options: ["candles", "toasts", "guests", "venues"], answerIdx: 0, hint: "No bolo → velas (candles)." },
        { prompt: "The invitation said 'black ___', so wear a suit.", options: ["party", "tie", "toast", "list"], answerIdx: 1, hint: "'black tie' = traje de gala." },
        { prompt: "She proposed a ___ to the newlyweds.", options: ["guest", "toast", "host", "venue"], answerIdx: 1, hint: "Fazer um brinde → toast." }),
      a('cv31_a9', 'mc',
        { prompt: "What does 'RSVP' ask you to do?", options: ["bring food", "confirm if you're coming", "arrive late", "leave early"], answerIdx: 1, hint: "Confirmar presença." },
        { prompt: "The person who organises and hosts a party is the:", options: ["guest", "host", "stranger", "caterer"], answerIdx: 1, hint: "Anfitrião → host." },
        { prompt: "'To gatecrash' a party means to:", options: ["leave early", "arrive uninvited", "bring a gift", "make a toast"], answerIdx: 1, hint: "Entrar sem convite." }),
      a('cv31_a10', 'mc',
        { prompt: "Which phrase accepts an invitation?", options: ["I'm afraid I can't.", "Count me in!", "Maybe another time.", "I'll pass."], answerIdx: 1, hint: "'Count me in' = tô dentro." },
        { prompt: "A 'toast' at a celebration is:", options: ["a type of bread only", "raising glasses to honour someone", "a party game", "an invitation"], answerIdx: 1, hint: "Brinde." },
        { prompt: "'The party is in full swing' means it is:", options: ["about to start", "at its liveliest", "already over", "cancelled"], answerIdx: 1, hint: "No auge." }),
    ],
  },
  cv41: {
    context: "Vocabulário emocional avançado para nuances: elated (eufórico), apprehensive (apreensivo), indifferent (indiferente), overwhelmed (sobrecarregado).",
    acts: [
      a('cv41_a1', 'match',
        { prompt: "Relacione a emoção com a tradução.", pairs: [{ left: "nervous", right: "nervoso" }, { left: "proud", right: "orgulhoso" }, { left: "bored", right: "entediado" }], hint: "Emoções comuns." },
        { prompt: "Relacione a emoção avançada com a tradução.", pairs: [{ left: "elated", right: "eufórico" }, { left: "apprehensive", right: "apreensivo" }, { left: "overwhelmed", right: "sobrecarregado" }, { left: "content", right: "satisfeito" }], hint: "Nuances." },
        { prompt: "Relacione a emoção sutil com a definição.", pairs: [{ left: "wistful", right: "gently sad and longing" }, { left: "indignant", right: "angry at unfairness" }, { left: "sheepish", right: "embarrassed and shy" }, { left: "smug", right: "annoyingly self-satisfied" }], hint: "Definições precisas." }),
      a('cv41_a2', 'match',
        { prompt: "Relacione a emoção com o oposto.", pairs: [{ left: "calm", right: "anxious" }, { left: "confident", right: "insecure" }, { left: "cheerful", right: "gloomy" }], hint: "Opostos." },
        { prompt: "Relacione a emoção avançada com o oposto.", pairs: [{ left: "elated", right: "despondent" }, { left: "serene", right: "agitated" }, { left: "indifferent", right: "passionate" }, { left: "hopeful", right: "despairing" }], hint: "Opostos refinados." },
        { prompt: "Relacione a emoção com sua causa típica.", pairs: [{ left: "overwhelmed", right: "too much to do" }, { left: "apprehensive", right: "an uncertain future" }, { left: "nostalgic", right: "old memories" }, { left: "indignant", right: "an injustice" }], hint: "Emoção → gatilho." }),
      a('cv41_a3', 'sort',
        { prompt: "Categorize a emoção como positiva ou negativa.", groups: ["Positive", "Negative"], items: [{ t: "elated", g: "Positive" }, { t: "despondent", g: "Negative" }, { t: "content", g: "Positive" }, { t: "resentful", g: "Negative" }], hint: "'despondent' = abatido; 'resentful' = ressentido." },
        { prompt: "Categorize a emoção pela família.", groups: ["Calm", "Agitated"], items: [{ t: "serene", g: "Calm" }, { t: "frantic", g: "Agitated" }, { t: "at ease", g: "Calm" }, { t: "flustered", g: "Agitated" }, { t: "composed", g: "Calm" }], hint: "'flustered' = atrapalhado; 'composed' = sereno." },
        { prompt: "Categorize a emoção pela intensidade.", groups: ["Slight", "Overwhelming"], items: [{ t: "peckish", g: "Slight" }, { t: "ravenous", g: "Overwhelming" }, { t: "uneasy", g: "Slight" }, { t: "petrified", g: "Overwhelming" }, { t: "irked", g: "Slight" }, { t: "enraged", g: "Overwhelming" }], hint: "Note: fome também escala (peckish → ravenous)." }),
      a('cv41_a4', 'gapdrop',
        { prompt: "After winning, she felt absolutely ___.", options: ["elated", "bored", "anxious", "indifferent"], answerIdx: 0, hint: "Ganhou → eufórica." },
        { prompt: "With so many tasks at once, he felt ___.", options: ["serene", "overwhelmed", "content", "amused"], answerIdx: 1, hint: "Muitas tarefas → sobrecarregado." },
        { prompt: "She remained ___ to the gossip, refusing to react.", options: ["indignant", "indifferent", "elated", "apprehensive"], answerIdx: 1, hint: "Não reagiu → indiferente." }),
      a('cv41_a5', 'gapdrop',
        { prompt: "He was ___ about the interview and couldn't sleep.", options: ["content", "apprehensive", "elated", "smug"], answerIdx: 1, hint: "Ansioso antes de algo → apreensivo." },
        { prompt: "Looking through old letters, she felt ___.", options: ["furious", "nostalgic", "petrified", "smug"], answerIdx: 1, hint: "Cartas antigas → nostálgica." },
        { prompt: "The unfair decision left the whole team ___.", options: ["elated", "indignant", "serene", "content"], answerIdx: 1, hint: "Injustiça → indignada." }),
      a('cv41_a6', 'gapdrop',
        { prompt: "After the holiday, she felt calm and ___.", options: ["frantic", "content", "resentful", "flustered"], answerIdx: 1, hint: "Relaxada → satisfeita (content)." },
        { prompt: "He gave a ___ smile, clearly pleased with himself.", options: ["sheepish", "smug", "wistful", "anxious"], answerIdx: 1, hint: "Convencido → smug." },
        { prompt: "Caught in the lie, she looked ___.", options: ["smug", "sheepish", "elated", "serene"], answerIdx: 1, hint: "Pego na mentira → envergonhada (sheepish)." }),
      a('cv41_a7', 'sort',
        { prompt: "Categorize a emoção.", groups: ["Happy family", "Sad family"], items: [{ t: "elated", g: "Happy family" }, { t: "despondent", g: "Sad family" }, { t: "cheerful", g: "Happy family" }, { t: "melancholy", g: "Sad family" }], hint: "Alegria x tristeza." },
        { prompt: "Categorize a emoção.", groups: ["Confident", "Insecure"], items: [{ t: "assured", g: "Confident" }, { t: "self-conscious", g: "Insecure" }, { t: "poised", g: "Confident" }, { t: "hesitant", g: "Insecure" }, { t: "assertive", g: "Confident" }], hint: "Seguro x inseguro." },
        { prompt: "Categorize a emoção pela conotação social.", groups: ["Endearing", "Off-putting"], items: [{ t: "sheepish", g: "Endearing" }, { t: "smug", g: "Off-putting" }, { t: "earnest", g: "Endearing" }, { t: "condescending", g: "Off-putting" }, { t: "humble", g: "Endearing" }], hint: "Cativante x que afasta." }),
      a('cv41_a8', 'match',
        { prompt: "Relacione a emoção com a expressão facial/corporal.", pairs: [{ left: "elated", right: "beaming smile" }, { left: "apprehensive", right: "biting nails" }, { left: "furious", right: "clenched fists" }], hint: "Corpo revela a emoção." },
        { prompt: "Relacione a emoção com a frase.", pairs: [{ left: "overwhelmed", right: "\"It's all too much.\"" }, { left: "indignant", right: "\"How dare they!\"" }, { left: "nostalgic", right: "\"Those were the days.\"" }, { left: "indifferent", right: "\"I couldn't care less.\"" }], hint: "O que a pessoa diria." },
        { prompt: "Relacione a emoção com um sinônimo mais comum.", pairs: [{ left: "elated", right: "thrilled" }, { left: "despondent", right: "hopeless" }, { left: "apprehensive", right: "worried" }, { left: "serene", right: "calm" }], hint: "Avançado → comum." }),
      a('cv41_a9', 'mc',
        { prompt: "'Elated' most nearly means:", options: ["extremely happy", "slightly bored", "very tired", "mildly annoyed"], answerIdx: 0, hint: "Eufórico." },
        { prompt: "Someone who is 'apprehensive' feels:", options: ["confident", "anxious about the future", "extremely proud", "totally relaxed"], answerIdx: 1, hint: "Apreensivo." },
        { prompt: "'Overwhelmed' describes someone who:", options: ["has nothing to do", "feels buried under too much", "feels completely calm", "is very bored"], answerIdx: 1, hint: "Sobrecarregado." }),
      a('cv41_a10', 'mc',
        { prompt: "Which word means 'annoyingly pleased with oneself'?", options: ["humble", "smug", "sheepish", "anxious"], answerIdx: 1, hint: "Convencido → smug." },
        { prompt: "'Indignant' is anger caused by:", options: ["hunger", "something unfair", "boredom", "cold weather"], answerIdx: 1, hint: "Raiva por injustiça." },
        { prompt: "A 'wistful' look is:", options: ["furious", "gently sad and longing", "extremely proud", "totally indifferent"], answerIdx: 1, hint: "Melancólico e saudoso." }),
    ],
  },
  cv46: {
    context: "Formal x informal na conversa. O formal usa frases completas e educadas ('Could you...?'); o informal usa contrações, gírias e frases curtas ('Can I...?', 'Gimme...').",
    acts: [
      a('cv46_a1', 'sort',
        { prompt: "Categorize a expressão como formal ou informal.", groups: ["Formal", "Informal"], items: [{ t: "Good morning", g: "Formal" }, { t: "Hey", g: "Informal" }, { t: "How do you do?", g: "Formal" }, { t: "What's up?", g: "Informal" }], hint: "Registro do cumprimento." },
        { prompt: "Categorize o pedido pelo registro.", groups: ["Formal", "Informal"], items: [{ t: "Could you possibly help me?", g: "Formal" }, { t: "Gimme a hand?", g: "Informal" }, { t: "Would you mind waiting?", g: "Formal" }, { t: "Hang on a sec", g: "Informal" }, { t: "I would appreciate it", g: "Formal" }], hint: "Educado/completo x curto/casual." },
        { prompt: "Categorize a frase pelo registro.", groups: ["Formal", "Informal"], items: [{ t: "I regret to inform you", g: "Formal" }, { t: "Bad news, mate", g: "Informal" }, { t: "I look forward to hearing from you", g: "Formal" }, { t: "Catch you later", g: "Informal" }, { t: "Please accept my apologies", g: "Formal" }, { t: "My bad, sorry!", g: "Informal" }], hint: "Contexto profissional x amigos." }),
      a('cv46_a2', 'sort',
        { prompt: "Categorize a despedida.", groups: ["Formal", "Informal"], items: [{ t: "Goodbye", g: "Formal" }, { t: "See ya", g: "Informal" }, { t: "Take care", g: "Informal" }, { t: "Farewell", g: "Formal" }], hint: "Despedidas." },
        { prompt: "Categorize a palavra pelo registro.", groups: ["Formal", "Informal"], items: [{ t: "purchase", g: "Formal" }, { t: "buy", g: "Informal" }, { t: "require", g: "Formal" }, { t: "need", g: "Informal" }, { t: "assist", g: "Formal" }], hint: "Sinônimos formais x neutros/informais." },
        { prompt: "Categorize o verbo frasal x formal (mesmo sentido).", groups: ["Formal", "Informal (phrasal)"], items: [{ t: "tolerate", g: "Formal" }, { t: "put up with", g: "Informal (phrasal)" }, { t: "postpone", g: "Formal" }, { t: "put off", g: "Informal (phrasal)" }, { t: "investigate", g: "Formal" }, { t: "look into", g: "Informal (phrasal)" }], hint: "Verbos frasais soam mais informais." }),
      a('cv46_a3', 'match',
        { prompt: "Relacione o informal com o formal.", pairs: [{ left: "Hi", right: "Good morning" }, { left: "Thanks", right: "Thank you very much" }, { left: "Sorry", right: "I apologise" }], hint: "Informal → formal." },
        { prompt: "Relacione o informal com o formal.", pairs: [{ left: "get", right: "receive" }, { left: "ask for", right: "request" }, { left: "help", right: "assist" }, { left: "show", right: "demonstrate" }], hint: "Verbos: informal → formal." },
        { prompt: "Relacione a frase informal com a formal.", pairs: [{ left: "Can you help?", right: "I would be grateful for your assistance" }, { left: "Let me know", right: "Please inform me" }, { left: "Sorry for the mess", right: "I apologise for the inconvenience" }, { left: "What do you think?", right: "I would value your opinion" }], hint: "Reformulação formal." }),
      a('cv46_a4', 'gapdrop',
        { prompt: "In a job interview, say: \"___ to meet you.\"", options: ["Yo, nice", "Pleased", "What's up", "Hiya"], answerIdx: 1, hint: "Formal → 'Pleased to meet you'." },
        { prompt: "To a close friend, you'd more likely say: \"___ a hand?\"", options: ["Would you kindly lend me", "Gimme", "I would appreciate", "Might you offer"], answerIdx: 1, hint: "Informal → 'Gimme a hand?'." },
        { prompt: "In a formal email, avoid 'ASAP' and write '___'.", options: ["right now", "at your earliest convenience", "in a sec", "pronto"], answerIdx: 1, hint: "Formal → 'at your earliest convenience'." }),
      a('cv46_a5', 'gapdrop',
        { prompt: "Formal: \"___ you mind opening the window?\"", options: ["Do", "Would", "Can't", "Gonna"], answerIdx: 1, hint: "'Would you mind' é mais educado." },
        { prompt: "Informal reply to 'How are you?': \"___.\"", options: ["I am quite well, thank you", "Not bad, you?", "I am in good health", "Very well indeed"], answerIdx: 1, hint: "Casual → 'Not bad, you?'." },
        { prompt: "Formal closing of a letter: \"___.\"", options: ["Cheers", "Later!", "Yours sincerely", "See ya"], answerIdx: 2, hint: "Carta formal → 'Yours sincerely'." }),
      a('cv46_a6', 'gapdrop',
        { prompt: "Informal: \"I ___ believe it!\" (short form)", options: ["cannot", "can't", "am not able to", "could not"], answerIdx: 1, hint: "Informal usa contrações → can't." },
        { prompt: "Formal writing avoids contractions, so write '___' not \"don't\".", options: ["dont", "do not", "doesn't", "won't"], answerIdx: 1, hint: "Formal → 'do not'." },
        { prompt: "Which is the more formal way to disagree?", options: ["No way!", "I'm afraid I see it differently", "You're wrong", "Nah"], answerIdx: 1, hint: "Discordar com educação." }),
      a('cv46_a7', 'match',
        { prompt: "Relacione o cumprimento com o registro.", pairs: [{ left: "How do you do?", right: "formal" }, { left: "What's up?", right: "informal" }, { left: "Good evening", right: "formal" }], hint: "Registro." },
        { prompt: "Relacione a gíria com o sentido neutro.", pairs: [{ left: "guy", right: "man" }, { left: "kid", right: "child" }, { left: "cash", right: "money" }, { left: "cop", right: "police officer" }], hint: "Gíria → neutro." },
        { prompt: "Relacione o phrasal informal com o verbo formal.", pairs: [{ left: "find out", right: "discover" }, { left: "give up", right: "abandon" }, { left: "set up", right: "establish" }, { left: "carry out", right: "conduct" }], hint: "Phrasal → formal." }),
      a('cv46_a8', 'sort',
        { prompt: "Categorize a situação pelo registro apropriado.", groups: ["Use formal", "Use informal"], items: [{ t: "job interview", g: "Use formal" }, { t: "texting a friend", g: "Use informal" }, { t: "email to a professor", g: "Use formal" }, { t: "chatting at a party", g: "Use informal" }], hint: "Quando usar cada um." },
        { prompt: "Categorize o e-mail pelo registro.", groups: ["Formal", "Informal"], items: [{ t: "Dear Sir or Madam", g: "Formal" }, { t: "Hey!", g: "Informal" }, { t: "I am writing to enquire", g: "Formal" }, { t: "Just a quick one", g: "Informal" }, { t: "Kind regards", g: "Formal" }], hint: "Aberturas e fechos." },
        { prompt: "Categorize a expressão pelo tom.", groups: ["Polite/Formal", "Blunt/Informal"], items: [{ t: "Might I suggest", g: "Polite/Formal" }, { t: "Just do this", g: "Blunt/Informal" }, { t: "I wonder if we could", g: "Polite/Formal" }, { t: "No chance", g: "Blunt/Informal" }, { t: "Would it be possible to", g: "Polite/Formal" }], hint: "Educado x direto." }),
      a('cv46_a9', 'mc',
        { prompt: "Which is more formal?", options: ["Wanna grab a coffee?", "Would you like to have a coffee?", "Coffee?", "Fancy a coffee?"], answerIdx: 1, hint: "Frase completa e educada." },
        { prompt: "In a formal email you should NOT write:", options: ["I am writing to...", "Kind regards", "Gonna send it later", "Please find attached"], answerIdx: 2, hint: "'Gonna' é informal." },
        { prompt: "The formal equivalent of 'ask for' is:", options: ["get", "request", "grab", "want"], answerIdx: 1, hint: "'request'." }),
      a('cv46_a10', 'mc',
        { prompt: "Which greeting is informal?", options: ["Good afternoon", "How do you do?", "Hey, what's up?", "Pleased to meet you"], answerIdx: 2, hint: "'Hey, what's up?'." },
        { prompt: "Which closing suits a formal letter?", options: ["Cheers", "Yours sincerely", "See ya", "Later"], answerIdx: 1, hint: "'Yours sincerely'." },
        { prompt: "'Put up with' is the informal way of saying:", options: ["enjoy", "tolerate", "request", "postpone"], answerIdx: 1, hint: "Tolerar." }),
    ],
  },
  cv47: {
    context: "Inglês casual e gírias: hang out (sair), chill (relaxar), gonna/wanna (going to/want to), awesome (incrível). Comuns na fala do dia a dia.",
    acts: [
      a('cv47_a1', 'match',
        { prompt: "Relacione a gíria com o sentido.", pairs: [{ left: "hang out", right: "spend time together" }, { left: "chill", right: "relax" }, { left: "awesome", right: "great" }], hint: "Gírias comuns." },
        { prompt: "Relacione a gíria com o sentido.", pairs: [{ left: "grab a bite", right: "eat something" }, { left: "hit the road", right: "leave / set off" }, { left: "broke", right: "having no money" }, { left: "starving", right: "very hungry" }], hint: "Expressões casuais." },
        { prompt: "Relacione a gíria com o sentido.", pairs: [{ left: "ghost someone", right: "suddenly stop replying" }, { left: "spill the tea", right: "share the gossip" }, { left: "low-key", right: "quietly / a little" }, { left: "hit different", right: "feel specially good" }], hint: "Gírias modernas." }),
      a('cv47_a2', 'match',
        { prompt: "Relacione a contração casual com a forma completa.", pairs: [{ left: "gonna", right: "going to" }, { left: "wanna", right: "want to" }, { left: "gotta", right: "have got to" }], hint: "Fala rápida." },
        { prompt: "Relacione a gíria com o sentido.", pairs: [{ left: "cool", right: "good / fine" }, { left: "guy", right: "man" }, { left: "buck", right: "dollar" }, { left: "folks", right: "people / parents" }], hint: "Vocabulário casual americano." },
        { prompt: "Relacione a expressão com o sentido.", pairs: [{ left: "no biggie", right: "not a problem" }, { left: "my bad", right: "my mistake" }, { left: "for real", right: "seriously / really" }, { left: "hang in there", right: "stay strong" }], hint: "Frases do dia a dia." }),
      a('cv47_a3', 'gapdrop',
        { prompt: "Do you want to ___ out this weekend?", options: ["hang", "chill", "grab", "hit"], answerIdx: 0, hint: "'hang out' = sair/passar tempo." },
        { prompt: "I'm ___ tired, I just want to chill at home.", options: ["gonna", "kinda", "wanna", "gotta"], answerIdx: 1, hint: "'kinda' = meio/um pouco." },
        { prompt: "She totally ___ me — hasn't replied in a week.", options: ["chilled", "ghosted", "grabbed", "crashed"], answerIdx: 1, hint: "Sumiu sem responder → ghosted." }),
      a('cv47_a4', 'gapdrop',
        { prompt: "That movie was ___! I loved it.", options: ["awful", "awesome", "boring", "okay"], answerIdx: 1, hint: "Adorou → awesome." },
        { prompt: "I can't buy it; I'm totally ___ this month.", options: ["rich", "broke", "cool", "starving"], answerIdx: 1, hint: "Sem dinheiro → broke." },
        { prompt: "Let's ___ the road before the traffic gets bad.", options: ["grab", "hit", "chill", "hang"], answerIdx: 1, hint: "'hit the road' = pôr o pé na estrada." }),
      a('cv47_a5', 'gapdrop',
        { prompt: "I'm ___ call you later, okay?", options: ["gonna", "wanna", "gotta", "kinda"], answerIdx: 0, hint: "'gonna' = going to." },
        { prompt: "I'm ___ go now, it's getting late.", options: ["gonna", "wanna", "gotta", "kinda"], answerIdx: 2, hint: "'gotta go' = tenho que ir." },
        { prompt: "\"Sorry I'm late!\" — \"No ___, don't worry.\"", options: ["way", "biggie", "chance", "clue"], answerIdx: 1, hint: "'no biggie' = sem problema." }),
      a('cv47_a6', 'sort',
        { prompt: "Categorize: gíria ou inglês padrão?", groups: ["Slang", "Standard"], items: [{ t: "wanna", g: "Slang" }, { t: "want to", g: "Standard" }, { t: "awesome", g: "Slang" }, { t: "excellent", g: "Standard" }], hint: "Gíria x padrão." },
        { prompt: "Categorize a expressão.", groups: ["Slang", "Standard"], items: [{ t: "grab a bite", g: "Slang" }, { t: "have a meal", g: "Standard" }, { t: "hang out", g: "Slang" }, { t: "spend time", g: "Standard" }, { t: "chill", g: "Slang" }], hint: "Casual x neutro." },
        { prompt: "Categorize a gíria pela emoção que expressa.", groups: ["Excited/Positive", "Annoyed/Negative"], items: [{ t: "awesome", g: "Excited/Positive" }, { t: "lame", g: "Annoyed/Negative" }, { t: "epic", g: "Excited/Positive" }, { t: "cringe", g: "Annoyed/Negative" }, { t: "hyped", g: "Excited/Positive" }, { t: "sketchy", g: "Annoyed/Negative" }], hint: "'lame' = sem graça; 'cringe' = vergonha alheia." }),
      a('cv47_a7', 'sort',
        { prompt: "Categorize a gíria pelo tema.", groups: ["Money", "Food", "Leaving"], items: [{ t: "broke", g: "Money" }, { t: "grab a bite", g: "Food" }, { t: "hit the road", g: "Leaving" }, { t: "bucks", g: "Money" }, { t: "starving", g: "Food" }], hint: "Dinheiro, comida, sair." },
        { prompt: "Categorize a expressão pela situação.", groups: ["Agreeing", "Refusing"], items: [{ t: "for sure", g: "Agreeing" }, { t: "no way", g: "Refusing" }, { t: "sounds good", g: "Agreeing" }, { t: "I'll pass", g: "Refusing" }, { t: "count me in", g: "Agreeing" }], hint: "Concordar x recusar." },
        { prompt: "Categorize: gíria ainda comum ou datada?", groups: ["Still common", "Dated"], items: [{ t: "cool", g: "Still common" }, { t: "groovy", g: "Dated" }, { t: "awesome", g: "Still common" }, { t: "the bee's knees", g: "Dated" }, { t: "chill", g: "Still common" }], hint: "'groovy' e 'bee's knees' soam antigas." }),
      a('cv47_a8', 'gapdrop',
        { prompt: "We just ___ at home and watched films.", options: ["chilled", "hit", "grabbed", "crashed"], answerIdx: 0, hint: "Relaxar em casa → chilled." },
        { prompt: "Let's ___ a bite before the show.", options: ["hang", "grab", "chill", "ghost"], answerIdx: 1, hint: "'grab a bite' = comer algo." },
        { prompt: "That party was ___ — best one all year!", options: ["lame", "epic", "sketchy", "cringe"], answerIdx: 1, hint: "Sensacional → epic." }),
      a('cv47_a9', 'mc',
        { prompt: "'To hang out' means to:", options: ["work hard", "spend time relaxing together", "argue", "leave quickly"], answerIdx: 1, hint: "Passar tempo junto." },
        { prompt: "If you're 'broke', you have:", options: ["lots of money", "no money", "a broken phone", "a new job"], answerIdx: 1, hint: "Sem grana." },
        { prompt: "'Gonna' is the casual form of:", options: ["gone to", "going to", "got to", "want to"], answerIdx: 1, hint: "going to." }),
      a('cv47_a10', 'mc',
        { prompt: "'Awesome' means:", options: ["terrible", "great", "boring", "expensive"], answerIdx: 1, hint: "Incrível." },
        { prompt: "If someone 'ghosts' you, they:", options: ["scare you", "suddenly stop replying", "visit at night", "help you"], answerIdx: 1, hint: "Somem sem responder." },
        { prompt: "Which sentence is the most casual?", options: ["I would like to relax.", "I'm gonna chill.", "I intend to rest.", "I shall unwind."], answerIdx: 1, hint: "'gonna chill' é o mais casual." }),
    ],
  },
})
